### ISSUE TITLE
feat(silent-refresh): Silently refresh the token

### ISSUE THREAD

**Issue by pekkah** [maxmantz/redux-oidc#1]
There's possibility of doing a silent "refresh" of the token before the current token expires by issuing in hidden "iframe" (or similar) a request to identity server with "&prompt=none" in query string. If the token is still valid  identity server will "refresh" the token. 

Is this feature already implemented in redux-oidc? 

sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient

**Comment by maxmantz** [comment]
This is not yet implemented -  I will have a look at the sample though and seew what I can do. Thank you!

**Comment by maxmantz** [comment]
I've had a look at the requirements and tried to implement it. The real difficulty here is that you need to provide an actual HTML file for the token manager to render in an `iframe`. So you would need to alter your webpack/gulp/grunt configuration to export another module which then builds into the `silentrefresh.html`. This is the part I'm looking to solve right now. I'm afraid there is no 'reacty' way to handle it.

**Comment by maxmantz** [comment]
I have published v1.1.11-beta1 (many 1s wow) to npm. The middleware now automatically detects when the `silent_renew` option in the config is set to `true` and triggers the silent renew flow.

As I've mentioned, the real difficulty I've had is to configure webpack in such a way, that a separate HTML file for the iframe gets generated. I've collaborated with a few awesome people to come up with an idea on how to solve this problem. [This](https://github.com/maxmantz/react-boilerplate/blob/v3.0.0/internals/webpack/webpack.dev.babel.js) is the configuration I use to build a separate `refresh.html` file. I know that your configuration might differ greatly from what I have. I would be happy to help as much as I can. Give it a shot :)

**Comment by maxmantz** [comment]
I've just tested it in my project and it works perfectly - will update the docs shortly. I would be happy to hear your feedback on how your configuration went in order to update the docs.

**Comment by maxmantz** [comment]
FYI I've fixed a bug in silent refresh. Please make sure you use the latest version (1.1.12).

**Comment by maxmantz** [comment]
Just out of curiosity: Did you try using the update already?

**Comment by pekkah** [comment]
It looks good. The team just went to another direction with it so I haven't been able to test it out. But I'm sure there's a need for it in the next projects.
