### ISSUE TITLE
user.state is undefined in callback

### ISSUE THREAD

**Issue by pekkah** [maxmantz/redux-oidc#10]
Before the state contained the redirectUrl but now it seems to be undefined in the callback page callback. In the example the redirect seems to be always to '/'.

**Comment by maxmantz** [comment]
What version are you using? What are the steps to reproduce this issue?

**Comment by pekkah** [comment]
Just upgraded to latest v2.2.0-beta.1

**Comment by pekkah** [comment]
OIDC config
```
 oidc: {
    client_id: '...',
    redirect_uri: 'http://localhost:8000/callback',
    response_type: 'id_token token',
    scope: 'openid ...',
    authority: '....',
    silent_redirect_url: 'http://localhost:8000/silent_renew.html',
    automaticSilentRenew: false,
    filterProtocolClaims: true,
    loadUserInfo: true,
    acr_values: '...',
    triggerAuthFlow: true
  }
```

**Comment by maxmantz** [comment]
There are changes to the middleware creator function call because of an issue (#9) reported yesterday. The signature of the function has changed.

Please see the [wiki](https://github.com/maxmantz/redux-oidc/wiki/3.-API#createoidcmiddlewareusermanager-shouldvalidate-triggerauthflow-callbackroute-loadeduser) and the [middleware creator function call](https://github.com/maxmantz/redux-oidc-example/blob/master/src/store.js#L11) in the example app.

My guess is that the change to `triggerAuthFlow` has been causing this. It is now `undefined` by default. You have to set it to `true` manually to get it to work.

**Comment by pekkah** [comment]
Yep, I read the wiki before upgrade. 

```
// oidc
const oidcMiddleware = createOidcMiddleware(userManager, () => true, false, '/callback');
```

**Comment by maxmantz** [comment]
Has `triggerAuthFlow` always been `false` in your settings before? The user state gets defined automatically when it is set to `true` in the [middleware](https://github.com/maxmantz/redux-oidc/blob/master/src/oidcMiddleware.js#L24). If it is false, nothing gets passed by default and the user's state is `undefined`. You need to call something like this manually:
```
userManager.signinRedirect({
    data: {
        redirectUrl: '/myRedirectUrl'
    }
})
```

**Comment by pekkah** [comment]
Hmm, which setting will it use then? The one coming from the configuration I pass to userManager {.., triggerAuthFlow: true } or the setting I pass to createOidcMiddlware as parameter?

**Comment by pekkah** [comment]
Sorry it seems that I misplaced the triggerAuthFlow first time to config I pass the userManager. Don't know where I got that part. Moving it to be passed as parameter to createOidMiddlware instead.

**Comment by maxmantz** [comment]
The `userManager` does not have a `triggerAuthFlow` setting. This is a flag for the middleware only. 

If it is `true` the middleware automatically redirects to the OIDC provider. 

If `false`, the user in the reducer gets cleared, but no redirect happens - for rendering a custom login screen for example, just like in the sample app. You will have to manually call the `userManager.signinRedirect(state)` function as described above to pass in the `redirectUrl` manually.

**Comment by pekkah** [comment]
Yes, I found the reason. We had a handler for doing redirect to auth when we get a unauthorized response from API call. This was firing up at the same time as the trigger auth flow was triggered.

**Comment by maxmantz** [comment]
Glad you were able to resolve the issue.

**Comment by dantovbein** [comment]
Hi @maxmantz ,I have a similar error when I'm trying to login through SSO (OneLogin platform) but I cannot find the solution. It the user is not logged or the session is expired it should be redirected to https://jamcity.onelogin.com/oidc/auth?client_id=7e640670-0f7a-0136-512f-06041460d132115152&nonce=ed6dafde735a020192d0ef2f60377da7&redirect_uri=https%3A%2F%2Fgsconfigv2.jamcity.com%2Fcallback&response_type=id_token&scope=openid&state=b9dcfbfc703dfa199f30572b7ac28f9e

The redirect_uri is working as expected (/callback) and to the success function, but when I log the response in successCallback I get this error:
```
index.js:56 Error: No matching state found in storage
    at oidc-client.min.js:1
```

According to your documentation https://github.com/maxmantz/redux-oidc I've installed these modules:
```
"redux-oidc": "^3.0.0-beta.16",
"oidc-client": "^1.4.1",
"oidc-client-fetch": "^1.2.2-fetch1",
```

**Index.js**

```
<Provider store={Store}>
    <OidcProvider store={Store} userManager={userManager}>
      <Router>
        <div>
          <Switch>
             <Route path={`/callback`} component={ CallbackPage } />
             <Route path={`/`} component={ App } />
            </Switch>
        </div>
      </Router>
    </OidcProvider>
</Provider>
```

**user-manager**
```
import { createUserManager } from "redux-oidc";
const clientId = "7e640670-0f7a-0136-512f-06041460d132115152";
export const baseUrl = `${window.location.protocol}//${window.location.hostname}:${window.location.port}`;

const userManagerConfig = {
  authority: 'https://******.onelogin.com/oidc/auth',
  client_id: clientId,
  redirect_uri: `${baseUrl}callback`,
  response_type: 'id_token token',
  scope: 'openid profile',
  post_logout_redirect_uri: `${baseUrl}/login`,
  silent_redirect_uri: `${baseUrl}/silent_renew.html`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true
};

const userManager = createUserManager(userManagerConfig);
export default userManager;
```

Store:
```
imports ....

const loggerMiddleware = store => next => action => {
  console.log("Action type:", action.type);
  console.log("Action payload:", action.payload);
  console.log("State before:", store.getState());
  next(action);
  console.log("State after:", store.getState());
};
const middleware = applyMiddleware(loggerMiddleware, thunk, promise);
const oidcMiddleware = createOidcMiddleware(userManager, () => true, true, `${baseUrl}callback`);
const Store = createStore(
  reducers,
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
  middleware,
  oidcMiddleware
);
console.log(window.sessionStorage); // Storage {length: 0}
console.log('1', window.localStorage); // 1 Storage {length: 0}
loadUser(Store, userManager);
console.log('2', window.localStorage); // 2 Storage {length: 0}
console.log(window.sessionStorage); // Storage {length: 0}
export default Store;
```

And this is the log (all is undefined)
store.js:13 Action type: redux-oidc/LOADING_USER
store.js:14 Action payload: undefined
store.js:13 Action type: redux-oidc/USER_EXPIRED
store.js:14 Action payload: undefined


I also tried with a login button through 

`userManager.signinRedirect();`

But I get this error

```
oidc-client.min.js:1 GET https://*****.onelogin.com/oidc/auth/.well-known/openid-configuration 404 (Not Found)
login:1 Failed to load https://jamcity.onelogin.com/oidc/auth/.well-known/openid-configuration: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gsconfigv2.jamcity.com' is therefore not allowed access. The response had HTTP status code 404.
oidc-client.min.js:1 Uncaught (in promise) Error: Network Error
    at XMLHttpRequest.o.onerror (oidc-client.min.js:1)
```

**Any help??**

**Comment by maxmantz** [comment]
You don't need oidc-client-fetch if you are using oidc-client-js. oidc-client-fetch is required when running SSR, or your SSR setup doesn't work with the classic oidc-client.
