### ISSUE TITLE
reducer TypeScript definition incorrect

### ISSUE THREAD

**Issue by shiznit013** [maxmantz/redux-oidc#101]
In index.d.ts, the definition for the reducer is

`export function reducer(state: UserState, action: Action<User | Error>): UserState;`

but I believe it should be

`export function reducer(state: UserState | undefined, action: Action<User | Error>): UserState;`

since the implementation is

`export default function reducer(state = initialState, action) { }`

By defaulting state to initialState, that means that state can be undefined. This results in the error

`Argument of type '{ oidc: (state: UserState, action: Action<User | Error>) => UserState; }' is not assignable to parameter of type 'ReducersMapObject<AppState, AnyAction>'.
  Types of property 'oidc' are incompatible.
    Type '(state: UserState, action: Action<User | Error>) => UserState' is not assignable to type 'Reducer<UserState, AnyAction>'.
      Types of parameters 'state' and 'state' are incompatible.
        Type 'UserState | undefined' is not assignable to type 'UserState'.
          Type 'undefined' is not assignable to type 'UserState'.`

My current workaround is to cast the ReducersMapObject as any, but then I lose the benefit of type safety.

**Comment by maxmantz** [comment]
I don't use typescript, so I cannot comment on the validity of your statement. Feel free to submit a PR if you think the current definitions are wrong.

**Comment by maxmantz** [comment]
Released in version 3.0.0
