### ISSUE TITLE
Redirect in Callback

### ISSUE THREAD

**Issue by jasonreact** [maxmantz/redux-oidc#103]
@maxmantz First, thank you for creating this great solution, we are very happy with it so far.

Referencing #74 

I am having a very similar issue to this because I am not sure where to put the solution that you mentioned above. Any help that you can provide is much appreciated. 

Where are you recommending this be placed?

`userManager.signinRedirect({ data: { redirectUrl: window.location.pathname } });`

Does this go in the Callback code or prior to the callback? Here is my Callback

`
class LoginCallback extends React.Component {
constructor(props) {
super(props);
}

render() {
    return (
        <CallbackComponent
            userManager={userManager}
            successCallback={() => this.props.dispatch(push('/landing'))}
            errorCallback={error => {
                this.props.dispatch(push("/"));
                console.error(error);
            }}
        >
            <div>Redirecting...</div>
        </CallbackComponent>
    );
}
}

function mapDispatchToProps(dispatch) {
return {
dispatch
};
}

export default connect(null, mapDispatchToProps)(LoginCallback);`

**Comment by maxmantz** [comment]
Hi,

the code you mention is called when the login process is started. So instead of being in the callback, it should be in the code taht is called when teh user clicks the login button or similar.

**Comment by jasonreact** [comment]
Thank you for answering this @maxmantz.  I will look to integrate this as you mentioned.  Keep up the good work!

**Comment by maxmantz** [comment]
Happy to help.
