### ISSUE TITLE
Getting few fields undefined in user data object after login successful using redux-oidc

### ISSUE THREAD

**Issue by MangeshGawai** [maxmantz/redux-oidc#106]
Below fields are getting undefined 
expires_at
session_state
expired
expires_in
scope
scopes

I tried below 2 type of configuration

1) 
const userManagerConfig = {
  client_id: 'client_id',
  redirect_uri: `${origin}/callback`,
  response_type: 'token id_token',
  scope: 'openid profile expires_at',
  authority: 'http://localhost:3001/api/v1/system/',
  filterProtocolClaims: true,
  loadUserInfo: true,
  metadata: {
     issuer: `${AUTHENTICATIONSRV_URL}`,
     jwks_uri: `${AUTHENTICATIONSRV_URL}/openid-configuration/keys`,
     userinfo_endpoint : `${AUTHENTICATIONSRV_URL}/userinfo`,
     authorization_endpoint: `${AUTHENTICATIONSRV_URL}/oauth`
   },
   signingKeys: signingKeys
}

2)
const userManagerConfig = {
  client_id: 'client_id',
  redirect_uri: `${origin}/callback`,
  response_type: 'token id_token',
  scope: 'openid profile expires_at',
  authority: 'http://localhost:3001/api/v1/system/',
  filterProtocolClaims: true,
  loadUserInfo: true
}

If anyone already fixed this issues please share the solution.

**Comment by maxmantz** [comment]
Your config looks fine, maybe this is related to your authentication server?

**Comment by maxmantz** [comment]
Closing this for now. Feel free to comment if your issue persists.

**Comment by lomboboo** [comment]
I have the same issue. This is my config:
```
const userManagerConfig = {
  authority: process.env.AUTHORITY_URL,    // The URL of the OIDC provider
  client_id: 'testClient',                 // Application's identifier registered in YaraSSO
  redirect_uri: redirectUri,               // The redirect URI to receive response (e.g token) from YaraSSO
  response_type: 'id_token token',         // The type of response desired from the YaraSSO
  scope: 'openid profile email',           // The scope being requested from the YaraSSO
  silent_redirect_uri: silentRedirectUri,  // URI for token refreshing
  post_logout_redirect_uri: postLogoutUri, // URI to redirect after log out
  automaticSilentRenew: true,              // Automatic attempt to renew token
  filterProtocolClaims: true,              // Should OIDC protocol claims be removed from profile
  loadUserInfo: true,                      // Additional identity data for the profile
};
```

And this is how I get `user`:
```
userManager.signinSilent()
      .then((result) => {
        // log the result if successfully obtained a token
        console.log('Succesfully obtained user', result)
      })
      ...
```

Result has `scope`, `state` values as `undefined`

**Comment by lomboboo** [comment]
@MangeshGawai  do you have any clue where the problem can lie on the server side?

**Comment by eZanmoto** [comment]
@lomboboo For example, I was experiencing a similar issue because I was using a version of Keycloak that had a bug where the `expires_at` field wasn't being returned for the Implicit Flow (https://github.com/IdentityModel/oidc-client-js/issues/534). There could be something similar happening with the server you're using, it could be useful to manually walk through the authentication flow that you're using and seeing what responses the server is returning.
