### ISSUE TITLE
Redux oidc callback called twice

### ISSUE THREAD

**Issue by dayan2** [maxmantz/redux-oidc#107]
Hi!
I have an issue please help me with this. The issue is my callback component is running twice when signinRedirect. Please find the following link. [Question on stackoverflow](https://stackoverflow.com/questions/50542672/redux-oidc-callback-called-twice)

Am i doing something wrong? Please assist me as soon as possible. thank you in advance.

**Comment by maxmantz** [comment]
I've answered on SO. Let's have the discussion there.
