### ISSUE TITLE
fails to build with create-react-app react-script

### ISSUE THREAD

**Issue by viveknaragude** [maxmantz/redux-oidc#108]
$` react-scripts build
Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:
./node_modules/oidc-client/src/Log.js:4
![capture](https://user-images.githubusercontent.com/25178257/40638274-eacbc1fe-6327-11e8-855d-a48cac4eb421.PNG)

**Comment by maxmantz** [comment]
This issue is related to oidc-client and not this library. Please raise an issue there.

**Comment by viveknaragude** [comment]
Yes i know but they says  upgrade to webpack 4.0? It uses the latest version of uglifyjs by default. which supports ECMA6. 

can you upgrade webpack 4.0 in your project

Thank you.

**Comment by maxmantz** [comment]
It is you who has to upgrade webpack - not me.

**Comment by viveknaragude** [comment]
ok Thank you maxmantz for your time
