### ISSUE TITLE
Better integration with redux-auth-wrapper package

### ISSUE THREAD

**Issue by jbellmore31g** [maxmantz/redux-oidc#11]
I am opening this issue as a result of the discussion in [issue #6](https://github.com/maxmantz/redux-oidc/issues/6).

The [redux-auth-wrapper](https://github.com/mjrussell/redux-auth-wrapper) package provides a higher order component to enforce authentication and authorization prior to components being loaded and the willMount and didMount methods being executed. Using this library allows for a common way to ensure a user is authenticated before accessing secure routes, and if not to redirect the user to a login page.

The benefit of using this library over a simpler check is the fact that it supports asynchronous loading of the authenticated user data. This solves the issue that was discussed in the previously mentioned issue above.

Essentially, the higher order component provided by the redux-auth-wrapper has a property, **authenticatingSelector**, which can be used to force it to wait until the user info is loaded using whatever asynchronous method is needed.

What is really needed to have a complete integration with that library is to be able to different between the following states:

1 - The user is not authenticated at all
2 - The user has authenticated but the authentication data has not been loaded yet (page was refreshed)
3 - The user is authenticated and the authentication data has been successfully loaded (page was not refreshed)

Right now it is impossible to tell the difference between sate 1 and state 2 so a redirect to the login page/process is always required whenever a user refreshes the page. This isn't really needed if we are able to load the user data from session storage, we just need the ability to wait for that to happen.

I am proposing, and will be opening up a PR for the following changes to allow us to differentiate between the different states:

1 - Adding a new property to the oidc state in the reducer called **isLoadingUser** which will default to true.
2 - On the following events, set the isLoadingUser to false, since they signify that the loading should have completed, either successfully or unsuccessfully: USER_EXPIRED, SILENT_RENEW_ERROR, USER_FOUND

With these changes, the redux-auth-wrapper package can be configured to look at the isLoadingUser state property and make the decision whether to redirect or not once that property is set to false, meaning the loaded should have completed one way or the other.

In addition to the PR the following repo provides an example of the use case:

https://github.com/jbellmore31g/redux-oidc-example

In this repo, the main route (/) is a protected route and requires the user to be logged in. If the user is has not authenticated yet they will be redirected to the /login route, which will also contain the route to redirect to after successful authentication. If the page is refresh you will notice there is no redirect to the /login route, it will simply wait for the user to be loaded and then USER_FOUND action to be dispatched. Once that has happened it will load the home component successfully.

I look forward to your thoughts on this, the tests should all be passing but will be curious if I overlooked anything. The one additional feature that is not in this PR but might be a good idea would be to have the IsLoadingUser set back to true whenever a silent renew starts. At the moment I only saw the action for whenever it fails, not for when it begins or is successful. Those would both be needed to support that use case I would think.

Thanks again!

**Comment by maxmantz** [comment]
I had a little glance over it and it seems good - the only real change is to the reducer adding the `isLoadingUser`, so it is definitely manageable. A question that came up with me is this - what should the `isLoadingUser` flag be when `SESSION_TERMINATED` has been dispatched (user logs off)? My idea is it should be false, because nothing is loading. Am I correct in the assumption the the redux-auth-wrapper will then display and alternative component (like an Unauthorized Page) when no user is present?

Thank you for your effort!

**Comment by jbellmore31g** [comment]
I would tend to agree that it should be set back to false.

For the redux-auth-wrapper component there is an **authSelector** property and a **authenticatingSelector** property. The authenticatingSelector property is what is checked to determine whether the user object is still being loaded and the authSelector is used to determine if the user is authenticated after the authenticatingSelector value is true.

So in the event of the user logging off (SESSION_TERMINATED) the isLoadingUser value would be set to false and the user object would be null. The redux-auth-wrapper would interpret this to mean that the async user loading is completed and since the value is null the user is **not** logged in would therefore redirect to login.

Glad to contribute!

**Comment by jbellmore31g** [comment]
Forgot to comment on having the `isLoadingUser` flag set to false by default and setting it to try in the middleware, I would agree provided there isn't a delay in the setting of that value to true.

I think it makes logical sense to have that value set to true whenever an attempt to authenticate, via user login, page reload or silent renew is started and set back to false whenever it completes with either success or error.

**Comment by maxmantz** [comment]
There won't be a delay - I'm currently working on it. Can you add me as a contributor to your fork of redux-oidc? I will push the changes when I'm done.

**Comment by jbellmore31g** [comment]
All set!

**Comment by maxmantz** [comment]
Merged the PR and released to npm. Thanks again.

**Comment by maxmantz** [comment]
If you agree, I will link your fork to the main page as an example on how to integrate this library with redux-auth-wrapper.

**Comment by jbellmore31g** [comment]
Absolutely! Happy to have you link to it.

Thanks again!

**Comment by phun-ky** [comment]
I would just like to comment here that this change: https://github.com/maxmantz/redux-oidc/compare/v2.2.0-beta.1...master#diff-3c3217c23ef5e3ae5ee305139c86bb31R52 is a breaking change.

We discovered this in a build step, where `npm install redux-oidc@^2.1.0-beta.3` became `npm install redux-oidc@^2.2.0` yesterday.

Probably nothing to do with it, but wanted to share some frustration. Keep up the good work

**Comment by maxmantz** [comment]
Thanks for your comment. It is a breaking change and I will fix it in an update. The `typeof()` statement is not the problem - this variable simply didn't exist before. I will implement a patch defining a default value `/callback` for this variable.

**Comment by maxmantz** [comment]
Fixed in version `2.2.1`.
