### ISSUE TITLE
oidc-client as dependency and peer dependency

### ISSUE THREAD

**Issue by mastertinner** [maxmantz/redux-oidc#110]
`oidc-client` is defined as a `dependency` and as a `peerDependcy` in `package.json`. To me, this doesn't make too much sense. Shouln't we rather decide for one of the two?

**Comment by maxmantz** [comment]
Absolutely. That somehow slipped in during the last release. I'll fix this ASAP.

**Comment by mastertinner** [comment]
Thanks, @maxmantz!

**Comment by maxmantz** [comment]
Should be fixed by the latest release.
