### ISSUE TITLE
oidc-client Frame window timed out issue

### ISSUE THREAD

**Issue by skvijay007** [maxmantz/redux-oidc#112]
oidc-client has fixed the issue pertaining to **Frame window timed out issue** which occurs in IE browsers in oidc-client 1.5.1 version. Which needs to be included in your dependencieas

**Comment by fa10** [comment]
Right now the **oidc-client 1.5.1** is not working with **redux-oidc**.

**Comment by giovani-milanez** [comment]
@fa10 I am having issues when running in production mode also.
Raised another issue [here](https://github.com/maxmantz/redux-oidc/issues/113).

**Comment by maxmantz** [comment]
This should be fixed in my latest release of version 3.0.0. 

This version removes oidc-client@1.5.1 from dependencies and adds it to peer dependencies. Try installing oidc-client@1.4.1 to see if it fixes your issue.
