### ISSUE TITLE
'Failed to parse id_token' error when using production build

### ISSUE THREAD

**Issue by giovani-milanez** [maxmantz/redux-oidc#113]
Hi,

I am currently using webpack 4.11.0 and all works great on development build 'webpack --mode development', however, when using production build 'webpack --mode production' I am getting
'Failed to parse id_token' error, after the redirect.

The error seems to be coming from ResponseValidator.js, _validateIdToken method, of oidc-client-js library.

It could be related to [this](https://github.com/IdentityModel/oidc-client-js/issues/583) issue.

I am using redux-oidc latestet version - 3.0.0-beta.17.
I am not exactly sure what version of oidc-client-js it depends on.

Could a possible upgrade of oidc-client-js version fix the problem?

Thanks

**Comment by maxmantz** [comment]
I've released v3.0.0. This version has `oidc-client` as a peer dependency. Try using oidc-client@1.4.1 to see if it resolves your issue.

**Comment by giovani-milanez** [comment]
I confirm that it works now, using oidc-client@1.5.0

**Comment by BertelBB** [comment]
I got the same issue when using v3.0.0 and oidc-client@1.4.1
Can confirm that updating oidc-client to v1.5.0 fixed the issue
