### ISSUE TITLE
CallbackComponent & OidcProvider StateType

### ISSUE THREAD

**Issue by JohnniesCode** [maxmantz/redux-oidc#115]
Hello Maxmantz,

i would like to use the latest version of redux-oidc but with typescript iam getting always the error, that the both components "CallbackComponent" and "OidcProvider" have not 2 arguments.
They only have the Prop type.
I would appreciate it, if you could fix this.

Thank you,
Johnny

**Comment by maxmantz** [comment]
Hi Johnny,

sadly I don't use TS. Feel free to add a PR which fixes your issue and I will include it in the next release.

Cheers!

**Comment by JohnniesCode** [comment]
Hey Maxmantz,

i run into problems with the push/pr and the token, iam sorry.
Could you change the two lines, that would be awesome :+1: 

Cheers,
Johnny

**Comment by maxmantz** [comment]
I'm currently on the road and don't find the time right now. I will add it as soon as I can.

**Comment by JohnniesCode** [comment]
Hi Maxmantz,

i could create a pr now, check it out :+1: 

Cheers,
Johnny

**Comment by JohnniesCode** [comment]
Thanks Maxmantz!

**Comment by maxmantz** [comment]
Changes have been published to version `3.0.1`. Thank you!

**Comment by chrisgbaker** [comment]
I believe this introduced a different typescript bug:

```
ERROR in \src\components\login-callback\index.tsx
./src/components/login-callback/index.tsx
[tsl] ERROR in \src\components\login-callback\index.tsx(50,17)
      TS2605: JSX element type 'CallbackComponent' is not a constructor function for JSX elements.
  Types of property 'state' are incompatible.
    Type 'void' is not assignable to type 'Readonly<{}>'.
```

**Comment by maxmantz** [comment]
That's unfortunate. I'm depending on TS users to do the typings. If you can provide a PR that fixes this, I'd be grateful. Thanks!

**Comment by spallister** [comment]
@maxmantz - Thanks for the great library!

Although I can't speak for @JohnniesCode, I suspect this issue might have actually been related to a change brought into v16.4.5. of @types/react via the PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26813).  In the end, the change was reverted via the PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26946), and has been packaged into v16.4.6 of @types/react.

Speaking for my myself, v3.0.0 redux-oidc was working just fine after upgrading to v16.4.6 of `@types/react`.  However, as of v3.0.1 redux-oidc, I now see the same issue as @chrisgbaker.

@JohnniesCode - Could you confirm that the typings issue you were previously seeing is resolved when using v3.0.0 of redux-oidc together with v16.4.6 of @types/react?  If so, it'd be great if this PR could simply be reverted.

**Comment by maxmantz** [comment]
Thank you for your research @spallister. I'd be happy to hear from @JohnniesCode to see whether or not your suggestion worked. If so, I will revert the change.

**Comment by JohnniesCode** [comment]
Hi spallister,

iam sorry i use react 15.6.1 and there is still the bug with redux-oidc 3.0.0 and typescript 2.3.4

Cheers
Johnny

**Comment by maxmantz** [comment]
Thank you for your reply @JohnniesCode. Can you upgrade your codebase to use the version of the typings @spallister suggested?

**Comment by JohnniesCode** [comment]
I Check it out

**Comment by JohnniesCode** [comment]
Cant use it with types 16.4.6

**Comment by maxmantz** [comment]
Does the error still occur if you revert back to redux-oidc version 3.0.0?

**Comment by JohnniesCode** [comment]
Yes

**Comment by maxmantz** [comment]
Since the change suggested by @spallister doesn't work for @JohnniesCode I'm hesitant to make a change. Do you guys have any additional suggestions that might solve this issue?

**Comment by spallister** [comment]
@JohnniesCode - To be sure, could you delete your node_modules directory and yarn.lock (or package-lock.json) file, ensure you have the following dependencies listed in your package.json (note these are exact versions):
- "react": "15.6.1"
- "react-dom": "15.6.1"
- "redux-oidc": "3.0.0"
- "typescript": "2.3.4"
- "@types/react": "15.6.1",

... then run a yarn (or npm) install.  

I tried doing this myself and could not reproduce the error you were seeing, as described at the top of this issue.

If you are able to reproduce the issue, can you copy and paste the exact error message you're seeing, here.

**Comment by maxmantz** [comment]
@JohnniesCode were you able to try out @spallister's suggestion?

**Comment by maxmantz** [comment]
Since we don't get a reply from @JohnniesCode I did some digging myself and tried the steps @spallister suggested.

My versions are:
- react@16.4.0,
- react-dom@16.4.0,
- @types/react@16.3.17,
- typescript@2.9.1

I can confirm that using redux-oidc@3.0.1 gives the error @chrisgbaker described. Rolling back to redux-oidc@3.0.0 fixed the issue.

I will therefore revert the changes introduced in version 3.0.1.

**Comment by maxmantz** [comment]
Fixed published to v3.0.2. Thanks to everyone for your help!

**Comment by activebiz** [comment]
Same issue here with 3.0.2

**Comment by maxmantz** [comment]
@colindekker @activebiz npm just recinded my login, therefore publishing didn't work. It should be available now.
