### ISSUE TITLE
Is there any way of blocking UI while user is loaded from storage?

### ISSUE THREAD

**Issue by aenciso** [maxmantz/redux-oidc#119]
I'm following the example provided but instead of displaying the Login component I am redirecting the user back to the Google login website.

homePage.js

```
...
function HomePage(props) {
  const { user } = props;

  return !user || user.expired ? userManager.signinRedirect() : <MainPage />;
}
...
```

The first time the user lands on the page it works fine, but when you reload the page, the user gets redirected before `LOADING_USER` finishes getting the user from the local storage.

Is there any way I can wait for loadUser to resolve before displaying any other component?

Thanks

**Comment by maxmantz** [comment]
`loadUser` returns a promise that you can wait for. You could modify your `HomePage` in such a way that it only redirects once `loadUser` has finished by using a custom flag or something similar.

**Comment by barrymichaeldoyle** [comment]
My solution is to implement a `LoadingScreen` component while the `isLoadingUser` prop is true.

Eg:
...
function HomePage(props) {
  const { isLoadingUser, user } = props;
  if (isLoadingUser) return <LoadingScreen />;
  return !user || user.expired ? userManager.signinRedirect() : <MainPage />;
}
...
