### ISSUE TITLE
Not able to use this module if project already has babel-pollyfills enabled.

### ISSUE THREAD

**Issue by abhishek4794** [maxmantz/redux-oidc#120]
I am getting following error while importing this module.
``` Can't have multiple instance of babel-polyfills```
According to oidc-client readme this should be used
```If you are using UMD/AMD and/or you already have included an ES6 polyfill (such as babel-polyfill.js) then you can include the UMD packaged version of the file from the ~/lib folder.```

Update :- I have modified import for oidc client in my forked repo and its working fine.
https://github.com/abhishek4794/redux-oidc/tree/master

**Comment by maxmantz** [comment]
I cannot reproduce the issue you mentioned. Which version of oidc-client are you using? I'll try again with your version. 

In addition, this seems to be an issue with oidc-client. Please raise an issue on their issue tracker to get direct feedback.
