### ISSUE TITLE
User is null after silent_renew is called after 5 seconds in IE11 only

### ISSUE THREAD

**Issue by sorenhoyer** [maxmantz/redux-oidc#122]
Using the latest version 3.0.2 and everything seems fine - except in IE11. 

While silent_renew is never really called on Chrome, after the page has loaded fine (without any issues) after approximately 5 seconds it is called in IE11, results i a 404 ( since I guess it's not really been set up) and the user in redux is changed to null as a consequence I guess. I added some console logs to the EXPIRED action but it doesn't seem as if it gets called, so the oidc redux user being set to null, has to be as a consequence of silent_renew failing.

But why is that even called after just 5 seconds to begin with? And why is this happening only in IE11?

Before upgrading to 3.0.2 and oidc-client 1.5.2 we used redux-oidc 2.2.1 and oidc-client 1.2.2 which worked fine in IE11 as well.

Anybody experiencing the same issues?

**Comment by sorenhoyer** [comment]
Hmm I saw this issue https://github.com/TomF-NVM which is somewhat similar to what we're experiencing...  with the slight twist that it works just fine in edge, firefox, chrome etc, but just not in IE11.

So I took a wild shot and tried to add `monitorSession: false` to the userManager configuration object, and on the positive side, the silent_renew.html requests has disappeared, the redux-oidc user is no longer set to null after 5 seconds which means that the app is no longer just displaying a loading icon 5 seconds in. Which is great! But what problems might setting `monitorSession: false` cause, if any?

**Comment by sorenhoyer** [comment]
> monitorSession [1.1.0]: (default: true): Will raise events for when user has performed a signout at the OP.

https://github.com/IdentityModel/oidc-client-js/wiki 

So does this indicate that the problem could be with the OP (OpenID Connect Identity Provider right?). Or does it point towards an issue with oidc-client?

Kind of weird that many other people report [similar issues](https://github.com/IdentityModel/oidc-client-js/search?q=monitorSession&type=Issues) but in other browsers, where it works for them in IE but not eg. Edge or Chrome. In my case it's only IE that is a problem.

**Comment by maxmantz** [comment]
Hi,

I'm not sure I can help you with this issue. This seems to be related to oidc-client. Please raise an issue there and see if you can get help there.
