### ISSUE TITLE
Multiple authentication bounces and infinite loop on iPad's Safari

### ISSUE THREAD

**Issue by b5imply** [maxmantz/redux-oidc#124]
#### Multiple authentication bounces and infinite loop on iPad's Safari
Got this problem with redux-oidc. We got our solution to work with `redux-oidc: "2.2.2-beta1"` but got introduced to some problems updating to version `3.0.x`

##### Situation
The app uses Single Sign on and sends the user to the authentication site to login using openId on ADFS. First problem came with some cookie policies from the backend. That got me in a infinite loop whatever platform. I went to fix the problem with [#651](https://github.com/IdentityModel/oidc-client-js/issues/651). We did what the solution suggested, we got one step further but not quite fixed yet.

##### Problem 
When sent back, we’ll get at least couple of bounces back and forth the authorization endpoint until we get past the flow. On iPad however, it goes in an infinite loop.

##### Attempted fixes
- If I remove the `loadUser()` in the store file, the infinite loop on the iPad goes away. However, if we try reaching a page in the site **directly**, it routes the user back to the main page (e.g. `https://site.com/item/1` routes back to main page `https://site.com`) and starts a new authentication flow.

- This goes away though if I add the `oidcMiddleware`. This fixes the URL problem on PC but introduces the infinite loop back on iPad.

This is difficult to debug, because many of these problems occur in production environment.

##### Screenshots chrome devTools
The network tab shows that it loops at least 4 times

![network](https://user-images.githubusercontent.com/15379150/46034442-e7ec8b80-c100-11e8-9df2-32ff4782dfca.JPG)

With middleware logger we can see what goes on in the redux store:

    Action type: redux-oidc/LOADING_USER
    Action payload: undefined
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/", 
	    search: "", 
	    hash: "", 
	    state: undefined, 
	    action: "POP",
    }
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/categories", 
	    search: "", 
	    hash: "", 
	    state: undefined, 
	    action: "REPLACE",
    }
    Action type: redux-oidc/USER_EXPIRED
    Action payload: undefined
    Action type: redux-oidc/LOADING_USER
    Action payload: undefined
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/callback", 
	    search: "", 
	    hash: "#access_token=XXX...&scope=openid&state=XXX...", 
	    state: undefined, 
	    action: "POP",
    }
    Action type: redux-oidc/USER_EXPIRED
    Action payload: undefined
    Action type: redux-oidc/LOADING_USER
    Action payload: undefined
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/callback", 
	    search: "", 
	    hash: "#access_token=XXX...&scope=openid&state=XXX...", 
	    state: undefined, 
	    action: "POP",
    }
    Action type: redux-oidc/USER_EXPIRED
    Action payload: undefined
    Action type: redux-oidc/LOADING_USER
    Action payload: undefined
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/callback", 
	    search: "", 
	    hash: "#access_token=XXX...&scope=openid&state=XXX...", 
	    state: undefined, 
	    action: "POP",
    }
    Action type: redux-oidc/USER_EXPIRED
    Action payload: undefined
    Action type: redux-oidc/USER_FOUND
    Action payload: User {
	    id_token: "xxx…", 
	    session_state: undefined, 
	    access_token: "xxx…", 
	    token_type: "bearer", 
	    scope: "openid", …}
    Action type: @@router/CALL_HISTORY_METHOD
    Action payload: {method: "replace", args: Array(1)}
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/", 
	    search: "", 
	    hash: "", 
	    state: undefined, 
	    action: "REPLACE", …}
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/home", 
	    search: "", 
	    hash: "", 
	    state: undefined, 
	    action: "REPLACE", …}
    Action type: redux-oidc/LOADING_USER
    Action payload: undefined
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
	    pathname: "/callback",  
	    hash: "#access_token=XXX...&scope=openid&state=XXX...",
	    action: "POP"
	    key: null
	    query: {}
	    search: ""
	    state: undefined
	}
    Action type: redux-oidc/USER_FOUND
    Action payload: 
	    User {
			access_token: "XXX..."
			expires_at: 1537899270
			id_token:"XXX..."
			profile: 
				auth_time: 1537867608
				pwd_exp: "4906587"
				sid: "S-1-5-21-443899186-691239191-1050887974-88508"
				sub: "dKSObMSs6ghva599VyDur9mMymnuPHHtteevyBScNB8="
				unique_name: "LV\CABRI"
				upn: "benjamin.rindaroy@avinor.no"
			scope: "openid"
			session_state: undefined
			state: undefined
			token_type: "bearer"
			expired: false
			expires_in: 1926
			scopes: [ 0: "openid" ]
		}
    Action type: redux-oidc/USER_FOUND
    Action payload: User { access_token: "XXX...", ... }
    Action type: @@router/CALL_HISTORY_METHOD
    Action payload: {method: "replace", args: Array(1)}
    Action type: @@router/LOCATION_CHANGE
    Action payload: {
		action:  "REPLACE"
		hash:  ""
		key:  "jdzr3p"
		pathname:  "/"
		query:  {}
		search:  ""
		state:  undefined
	}
    Action type: @@router/LOCATION_CHANGE
	Action payload: {
		action:  "REPLACE"
		hash:  ""
		key:  "f6d0xr"
		pathname:  "/categories"
		query:  {}
		search:  ""
		state:  undefined
    }
    ... Normal actions
Note that many lines where censored for sensitive info which is represented as `XXX...`

Any help is appreciated.

**Comment by maxmantz** [comment]
Sorry for the late reply. I just tried this with Safari on my own iPad but I couldn't reproduce the issue. Were you able to resolve this problem?

**Comment by b5imply** [comment]
Hello maxmantz.

I use ADFS to authenticate.

As I stated, it's hard to debug. Maybe my UserManager config file can help:

	import { createUserManager } from  'redux-oidc'
	
	const authURL = <AUTH URL>
	const clientID = <CLIENT ID>
	const apiURL = <API URL>
	
	const  userManagerConfig  = {
		authority:  authURL,
		client_id:  clientID,
		redirect_uri:  `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
		response_type:  'id_token token',
		scope:  'openid',
		resource:  apiURL,

		metadata: {
			issuer: authURL,
			authorization_endpoint: authURL + '/oauth2/authorize',
			userinfo_endpoint: authURL + '/userinfo',
			end_session_endpoint: authURL +  '/oauth2/logout',
			token_endpoint: authURL +  '/oauth2/token',
			jwks_uri:  '/adfs/discovery/keys',
		},
		
		loadUserInfo:  false,
		filterProtocolClaims:  true,
		post_logout_redirect_uri:  `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/loggedout`,
		silent_redirect_uri:  `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew.html`,
		automaticSilentRenew:  true,
		silentRequestTimeout:  30000,
		revokeAccessTokenOnSignout:  true,
	}
	
	const  userManager  =  createUserManager(userManagerConfig)
	
	export  default  userManager

**\<AUTH URL\>** = The URL to the active directory adfs authorization page.
**\<CLIENT ID\>** = the client id to the application.
**\<API URL\>** = URL to the dotnetcore API.

**Comment by maxmantz** [comment]
OK, I'll try to troubleshoot.

First of all I strongly recommend using the `loadUser` function instead of the middleware. The middleware is only there for legacy purposes or when no silent renew is configured. Since you have silent renew activated in your config, `loadUser` should be used.

I also recommend using `localStorage` to store the userManager's user data. You can find out how to do that in the oidc-client wiki. The reason for this is that the userManager stores the user information in `sessionStorage` by default, which gets cleared when the tab is closed. This makes it so that every time your app opens, a new authentication flow is started, even when there might still be a valid token in storage. It also allows for several tabs of your app to be open at once and share the same user data.

One problem you've described is that after a successful authentication flow, the app is redirected to the root `'/'` of the app. This can be fixed by sending data with the authentication request. You can modify your call to `userManager.signinRedirect()` like this:

```
userManager.signinRedirect({
    data: {
      path: window.location.pathname
    }
});
```

If your authentication provider supports this, a successful token callback has this information in the `state` property of the returned user. This can then be used in the `CallbackComponent` like this:

```
<CallbackComponent successCallback={ user => dispatch(push(user.state.path)) } />
```

As for the infinite loop I'm afraid I cannot help you because I don't have enough information. My guess is that [`loadUser`](https://github.com/maxmantz/redux-oidc/blob/master/src/helpers/loadUser.js) runs, finds no valid user data, then dispatches `USER_EXPIRED`, which in turn triggers the milddeware to start the auth flow - a process which is repeated ad infinitum.
 
The example app demonstrates how to separate the two by allowing for no user to be present (this is when the login view is shown). Maybe you can find additional help there.

Hope this helps as a starting point for your investigation into this issue. Feel free to comment if you find anything else out.

**Comment by b5imply** [comment]
Alright. My application works now. Here is what I found out:
 - The app have a saga reducer with `USER_EXPIRED` action and implemented a signinRedirect. Old code. **\<Removed>**
 - in `UserManager.js` added the `userStore:  new  WebStorageStateStore({ store:  window.localStorage })` and I can now see the user is now stored in the localSession storage. **\<Added>**
 - CallbackPage now has `push(user.state.path)` in `successCallback`. This wouldn't work with the first point because it `user.state.path` value is `/callback` **\<Added>**
 - Store now has only `loadUser(store, userManager)` **\<Changed>**
 - LoginPage now have extra parameters in `userManager.signinRedirect({ data: { path:  window.location.pathname } })` order for CallbackPage `successCallback` to get the right path. **\<Added>**

The saver here is the `WebStorageStateStore` and managing the paths.

Thanks **maxmantz**. I like that you take your time and investigate help others.
