### ISSUE TITLE
Is there any working example for redux-oidc with SSR?

### ISSUE THREAD

**Issue by stg609** [maxmantz/redux-oidc#129]
I just tried the latest redux-oidc (3.1.0) with oidc-client (1.5.4)。But still get the following exception when used with server side rendering.
> C:\xxx\react-ssr-master\node_modules\oidc-client\lib\oidc-client.min.js:1
(function (exports, require, module, __filename, __dirname) { !function webpackUniversalModuleDefinition(e,t){if("object"==typeof exports&&"object"==typeof module)module.exports=t();else if("function"==typeof define&&define.amd)define([],t);else{var r=t();for(var i in r)("object"==typeof exports?exports:e)[i]=r[i]}}(window,function(){return function(e){var t={};function __webpack_require__(r){if(t[r])return t[r].exports;var i=t[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,__webpack_require__),i.l=!0,i.exports}return __webpack_require__.m=e,__webpack_require__.c=t,__webpack_require__.d=function(e,t,r){__webpack_require__.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},__webpack_require__.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},__webpa
ReferenceError: window is not defined
    at Object.<anonymous> (C:\xxx\react-ssr-master\node_modules\oidc-client\lib\oidc-client.min.js:1:257)
    at Module._compile (module.js:653:30)
    at Module._extensions..js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\xxx\react-ssr-master\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at t (C:\xxx\react-ssr-master\node_modules\redux-oidc\dist\redux-oidc.js:1:182)

It seems the error was raised while loading module, and actually I never call the related code as you can see below.
```
import React from "react";
import { connect } from "react-redux";
import { createUserManager } from "redux-oidc";
//omit others

const config = {
    authority: "http://localhost:5000",
    client_id: "WebSPA",
    redirect_uri: "http://localhost:9000/callback",
    response_type: "id_token token",
    scope: "openid profile",
    post_logout_redirect_uri: "http://localhost:9000",
};

class Home extends React.Component {
    //the function is not used
    onLoginButtonClick( ) {
        //the exception will disappear if comment out the following line and the import.
        const mgr = createUserManager( config ); 
    }
    render( ) {
          return (
            <div>
                <h2>HOME</h2>                
            </div>
        );
    }
}

//omit others
```

**Comment by stg609** [comment]
Finally, I have figured it out. The issue is caused by oidc-client, and my temporary solution is replace `window` with `(typeof window === 'undefined'?undefined:window)` in node_modules\oidc-client\lib\oidc-client.min.js

**Comment by BradyEdgar94** [comment]
@stg609 Do you happen to have this node_modules\oidc-client\lib\oidc-client.min.js file with your changes implemented? I am trying to do the same thing as you but it keeps breaking that script.

**Comment by maxmantz** [comment]
Hi @stg609, It looks like your fix might be helpful for the fols at `oidc-client`. It would be great if you could share your findings there.

**Comment by blerimj** [comment]
@JohnniesCode Can you share your findings here? Is that a stable solution for you?
