### ISSUE TITLE
Window undefined error with Version ^3.1.0 still

### ISSUE THREAD

**Issue by BradyEdgar94** [maxmantz/redux-oidc#131]
I have been fighting with a window undefined error for quite a while now and have had no luck fixing it. In the documentation it says that version 3 fixed the window undefined issue but I still seem to get it. It seems like any time I import something like `createUserManager` I get a window error.

I am using these two package version which my the README says I shouldn't be getting this error anymore.
"oidc-client": "^1.5.4",
"redux-oidc": "^3.1.0",

This is the exact error I am getting
![screen shot 2018-11-25 at 5 07 37 pm](https://user-images.githubusercontent.com/15221534/48975459-196bde00-f0d5-11e8-930d-0a7cdf91881d.png)

**Comment by maxmantz** [comment]
Hi @BradyEdgar94 and thanks @aenciso for trying to fix the problem. The error you are seeing is happening inside of `oidc-client`. 

Are you using SSR? If so, this could explain the problem. `oidc-client` currently doesn't support SSR.

**Comment by BradyEdgar94** [comment]
Hi @maxmantz yes, I am using next.js which does use SSR which would likely be the issue. I just thought by reading the V3 documentation that SSR was supported when using redux-oidc so I thought it shouldn't be a problem.

Thanks

**Comment by maxmantz** [comment]
While this library is SSR ready, oidc-client is built relying on `window` and is therefore not SSR ready. There are discussions about this on the oidc-client issue tracker though. Maybe you will find an answer there.
