### ISSUE TITLE
USER_EXPIRED dispatch after renew token

### ISSUE THREAD

**Issue by Rasfuranku** [maxmantz/redux-oidc#132]
First of all, thanks for the amazing work you are doing with the library. 

So, I am getting a frame timeout when trying to do the silent renew, but I managed it just redirecting the provider to the callback url and with that, I am getting the new access token from my provider. Please note I just mentioned this in order to give more context about the issue, because I don't think is directly related with the library as I am getting the same error using the provider's SDK. 

Now, the real issue I am concerned is after renew the token several times (we are doing this in order to manage an idle users), the EXPIRING_USER and EXPIRED_USER are still being dispatched for the first token the user get when log in the application. I am updating the store every time I get a new token and this dispatch effectively the USER_FOUND action but still the user will be log out and the session time is not being dragged on.

My userManagerConfig:

```
const userManagerConfig = {client_id: envConfig.AUTH0_CLIENT_ID,
    redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ""}/callback`,
    response_type: "code token id_token",
    scope: "openid profile read",
    authority: envConfig.AUTH0_URI,
    silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ""}/callback`,
    automaticSilentRenew: false,
    filterProtocolClaims: true,
    loadUserInfo: true,
    extraQueryParams: {
        audience: "http://etl-dev.onroute.xyz/v1",
    }
};
```

I am calling the silent renew one time per minute `await userManager.signinSilent();`

And dispatching an action to update the store in the `callbackSuccess` method.

```
successCallback(user) {
        this.props.updateUser(user);
}
```

**Comment by aenciso** [comment]
You don't need to call silent renew manually, you can set automaticSilentRenew to true and it will automatically renew your token 1min before the token expires. Have you configure your reducer properly? it seems like the store is not being updated on time.

**Comment by maxmantz** [comment]
Thanks @Rasfuranku for the compliments and @aenciso for the reply. In addition to @aenciso 's suggestion, the silent renewal of tokens happens in an iframe which is loaded into the page. You also don't need to call `signinSilent`, the userManager will take care of renewal automatically five minutes before token expiration. 

There might be an issue with the iframe loading in. Also if you could share your store setup (where you initially set up the `loadUser` helper) & the root of your app (where you register the `OidcProvider`), I can possibly help you further.

**Comment by Rasfuranku** [comment]
Thanks @maxmantz and @aenciso for your reply. 
I know that userManager will renew the token before it expires, but in this case, we do need to renew it the token manually.
Now, I think indeed the store is not being updated, I am being debugging and on every request I always have the first token stored even after several successful renews.

My store:
```
import { createStore, combineReducers, applyMiddleware } from "redux";
import thunk from "redux-thunk";
import promise from "redux-promise-middleware";
import modalReducer from "./reducers/modalReducer";
import { loadUser, reducer as oidcReducer } from "redux-oidc";

let middleware = [thunk, promise()];

const store = createStore(
    combineReducers({
        modalReducer,
        oidcReducer,
    }),
    {},
    applyMiddleware(...middleware)
);
loadUser(store, userManager);

export default store;
```

And my root:
```
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";

import Routes from "./redux/routes";
import store from "./redux/store";
import { OidcProvider } from "redux-oidc";
import { userManager } from "./redux/userManager";

ReactDOM.render(
    <Provider store={store}>
      <OidcProvider store={store} userManager={userManager}>
        <Routes />
      </OidcProvider>
    </Provider>,
    document.getElementById("root")
);
```

I noticed the store is being overwritten, that means that for some request I have the current token but for others I will get the first one.
Thanks.

**Comment by maxmantz** [comment]
From the config I cannot see why this would happen. Maybe something in your request API gets the incorrect token? What you've shown here looks fine.

**Comment by s-pilkhwal** [comment]
@Rasfuranku I know this is a very old post, but do you remember if you were able to figure out what was going wrong ? I too am facing similar issue where the token is not updated in redux after silent renewal.  I can see the latest token in localStorage and stale/old token in redux state under redux-oidc/USER_FOUND
