### ISSUE TITLE
Error: No state in response

### ISSUE THREAD

**Issue by aenciso** [maxmantz/redux-oidc#133]
When I use this configuration:

`const userManagerConfig = {
  client_id: CLIENT_ID,
  redirect_uri: `${redirectUrl}/${CALLBACK}`,
  response_type: 'token id_token',
  authority: AUTH_URL,
  silent_redirect_uri: `${redirectUrl}/${SILENT_RENEW}`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: false,
  post_logout_redirect_uri: `${redirectUrl}/${LOGOUT}`
};`

Everything works fine but if I set

`response_type: 'code'`

I get **Error: No state in response**

Thanks

**Comment by maxmantz** [comment]
This looks like it is a question better asked at the `oidc-client` issue tracker. However as a small pointer, read [this](https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660). When you only supply `code` as the response type, you will not get a token from the token endpoint, which possibly explains the behavior you're seeing. Try to append `openid` to the response type to see if this fixes the issue.

**Comment by aenciso** [comment]
Excellent. Thanks a lot for this awesome library.
