### ISSUE TITLE
userManager.signOutRedirect

### ISSUE THREAD

**Issue by jeinz11** [maxmantz/redux-oidc#134]
Hi im having an issue when using userManager.signoutRedirect() whenever i call this method its just refreshing and callbackpage is called

**Code**:

```
import { createUserManager } from "redux-oidc";

const userManagerConfig = {
    client_id: 'spa',
    redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
    response_type: 'token id_token',
    scope: 'openid profile api1',
    authority: 'http://localhost:5000',
    silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew.html`,
    automaticSilentRenew: true,
    filterProtocolClaims: true,
    loadUserInfo: true,
    monitorSession: true
};

const userManager = createUserManager(userManagerConfig);

export default userManager;


```
I already tried adding `userManager.clearStaleState();` before signoutRedirect but it doesnt work either.
when im checking the network trace it doesnt call end session as well

however when i try to remove  `<OidcProvider store={store} userManager={userManager}>` its working but im having trouble when logging-in in the first load thats why i didnt proceed to that path

thanks for helping

**Comment by jeinz11** [comment]
Hi maxmantz,

thanks for replying, i was using loaduser base on the example app and docs

**Comment by maxmantz** [comment]
`loadUser` is the correct way to do things. Your config looks fine as well. From the information here I cannot see why this would happen.

**Comment by nick-cromwell** [comment]
Calling `UserManager.removeUser();` before `UserManager.signoutRedirect();` appears to resolve this.

**Comment by maxmantz** [comment]
Thank you for your help @nick-cromwell .

@jeinz11 did this solve your issue?

**Comment by yosbeleg89** [comment]
@maxmantz I'm having the same issue, calling the `removeUser()` works for me, but is it the correct way to do it?

**Comment by maxmantz** [comment]
`removeUser()` removes the user data from the client app, `signoutRedirect()` logs you out completely at the auth server. Please refer to the `oidc-client` wiki for further documentation.

**Comment by yosbeleg89** [comment]
Thanks @maxmantz, I read the documentation, but also checked the code and I noticed that the oidc-client does call `removeUser()`, this is why I'm wondering why it should be called twice.
https://github.com/IdentityModel/oidc-client-js/blob/dev/src/UserManager.js#L423

**Comment by maxmantz** [comment]
It "shouldn't" be called twice, but there is also no harm in doing so. If your signout only works if you call both, it might hint at a deeper issue with your app's configuration.

**Comment by yosbeleg89** [comment]
Thanks @maxmantz, and yes, you are right, I think it is related with another issue, maybe the component being re-rendered when the button is clicked, I'm not sure, for now the workaound works, but I'm trying to know what the real issue is.

**Comment by nick-cromwell** [comment]
@yosbeleg89 Thanks for pointing out the `removeUser()` as part of signoutRedirect. I don't know that `removeUser()` has been the resolution I first thought it was. I may be starting to see effects of a misconfiguration again when signing out so I'm going to look at this again over the next couple days. If I come across anything I'll respond back.
