### ISSUE TITLE
Private routing with oidc

### ISSUE THREAD

**Issue by goetzmi** [maxmantz/redux-oidc#136]
Hello,

im a newbie at developing with react, so please forgive me this maybe dump question. At the moment
I wrote a react-redux webpage communicating with a server made with asp.net core. (both using the lastes version of each technique). The server uses IdentityServer4 for user authentication - thats the reason why I`m using your react-oidc wrapper. All works fine, but I got one Problem -> the private routing. My current dirty solution is to save the token_id at the local browser storage and every time the react router needs to navigate it checks if there is some token_id exisiting. If it is, the router will navigate to the next route pushed. 

I don`t like the way I`ve currently done this in due to the fact that it`s easily be bypassed by only entering some values with the right key to the storage. I know that the user then has no way to get his hands on the server data, but I don`t want him to be able to navigate throught the pages as well.

Do you have any idea how to solve this with redux-oidc? I`ve found no function for verifying some token_id or anything like that.

This is my current private route:

`export const PrivateRoute = ({ component: Component, ...rest }) => (
  <Route
    {...rest}
    render={props =>
      localStorage.getItem("user_id") ? (
        <Component {...props} />
      ) : (
        <Redirect to="/" />
      )
    }
  />
);`

Thank you very much in advance.

**Comment by maxmantz** [comment]
Hi there,

authorization on the client side is very simple. The userManager decodes the token from the server and puts its content into the user object stored in the reducer. This means that you can add claims to your tokane which is then used by both serer and client. You can then use this information to authorize your users, for example

```
render() {
  if (!this.props.user["ADMIN"]) {
     return <UnauthorizedPage />;
  }

  return <AdminPage />
}
```

The specifics are down to your preferences. Hope this helps.

**Comment by goetzmi** [comment]
Thank you very much! I forgot about the user at the store given by your reducer. This solved my Problem.. at the end my solution looks different than yours, but that doesnt matter.
