### ISSUE TITLE
Passing ui_locales to identityserver 

### ISSUE THREAD

**Issue by saeidehv** [maxmantz/redux-oidc#137]
Is there any way to pass my application selected culture by user ( from a menu which user can change it anytime) in UserManager.signinRedirect();

I tried to set it in the config 
const userManagerConfig = {
    client_id: clientId,
  ....

    extraQueryParams: {
        
        'ui_locales': navigator.language.toLowerCase()
    }
};
const UserManager = createUserManager(userManagerConfig);

but it is not updating when user change the culture in the application.

**Comment by maxmantz** [comment]
You can pass parameters using signinRedirect. Please refer to the oidc-client wiki to see how it is done.
