### ISSUE TITLE
Redux 6

### ISSUE THREAD

**Issue by maganuk** [maxmantz/redux-oidc#138]
Hi,

I'm having issues using this with Redux 6. Does the library need an upgrade? 

Thanks

Vishal

**Comment by maxmantz** [comment]
Hi @maganuk ,

this library doesn't have a direct dependency on react-redux, so there shouldn't be an issue. If you are having issues, please share them here (error messages, stacktraces etc.) so that we can solve them together.

**Comment by fa10** [comment]
@maxmantz, I got some issues is some tests. Where I set the state, but it suddenly changes the state to user is null. I just upgraded to react-redux v6

**Comment by maganuk** [comment]
Same here

**Comment by maxmantz** [comment]
Sorry for not getting back to this but I currently lack the time to investigate this further. Also I don't know enough about specifics within your projects to see whether or not this is a bug or not,

The interaction with redux are in [the reducers](https://github.com/maxmantz/redux-oidc/tree/master/src/reducer) and userManager actions are bound in the [OidcProvider](https://github.com/maxmantz/redux-oidc/blob/master/src/OidcProvider.js). All in all there is very little magic to it and I don't see how this could affect redux.

**Comment by maganuk** [comment]
The issue resolved itself after updated connected-react-router (6.2.2) and redux-auth-wrapper (2.1.0)
