### ISSUE TITLE
User does not force to login again with their password and username after logout

### ISSUE THREAD

**Issue by johnnyliang213** [maxmantz/redux-oidc#139]
Hi, first of all thanks for the amazing work to get the oidc library works with the react redux app. I encounter a bug in my application where after user logout by calling `userManager.removeUser()`, the user does not require to relogin with their password and username. Anyone can click the `login` button and sign in as the previous user. I use oneLogin and I configured the oidc redux as following: 

```
import { createUserManager } from 'redux-oidc';

const userManagerConfig = {
  authority: 'https://xxxxx.onelogin.com/oidc',
  client_id: 'xxxxx-xxxxxx-xxxxxx',
  redirect_uri: 'http://localhost:3000/oauth/callback',
  post_logout_redirect_uri: 'http://localhost:3000',
  response_type: 'id_token token',
  scope: 'openid profile email groups',
  filterProtocolClaims: true,
  loadUserInfo: true,
  automaticSilentRenew: true
}

const userManager = createUserManager(userManagerConfig);

export default userManager;

```
I also tried to call `userManager. signoutRedirect()` but still couldn't resolve the problem.

**Comment by maxmantz** [comment]
Hi and many thanks for the kind words!

`removeUser` only removes the user from the local storage. When the login button is clicked again, the app requests a new token from the auth server. When the user is still authenticated with the auth server, he doesn't need to enter his credentials again. To completely sign off a user on both the app and the auth server, use `signoutRedirect` instead.

**Comment by attiqeurrehman** [comment]
@johnnyliang213 I am facing the same issue, did you managed to resolved it? 

@maxmantz I used the `signoutRedirect ` but result is same it's not removing the **isdrv** cookie and because of that it's signing in as previous user again and again.
