### ISSUE TITLE
Usage with react-router hashHistory

### ISSUE THREAD

**Issue by jonaskello** [maxmantz/redux-oidc#14]
I'm running into some trouble with the callback component as I am using react-router with hashHistory instead of browserHistory. If I setup the callback route with a splat like `/callback/*` and use the splat part as fragment to send to userManager it works, like this: `userManager.signinRedirectCallback(fragment)`.

However that is not possible with CallbackComponent as there is no way to customize the call. What I think would be needed is that [here](https://github.com/maxmantz/redux-oidc/blob/master/src/CallbackComponent.js#L16) in CallbackComponent it should be possible to customize the userManager.signinRedirectCallback() call to include a fragment you extract yourself. Maybe by passing a callback into CallbackComponent.

**Comment by jonaskello** [comment]
Or maybe even simpler is to add fragment as an optional prop to callback component, and if it exists it wil pass it to userManager.signinRedirectCallback()`.

**Comment by maxmantz** [comment]
I will look into this

**Comment by maxmantz** [comment]
I've just published version `2.2.0-beta.3` which adds a prop called `route` to the callback component. I hope this fixes your issue.

**Comment by jonaskello** [comment]
I've actually switched to use browserHistory now so I cannot test, but I had a look in the code and it seems to do what I wanted. Not sure if `route` is the best name for the prop though. I think the parameter that goes into `userManager.signinRedirectCallback` is called fragment in the oidc-client library itself. What you need to send in the prop is the part of the route/url that goes after the hash in the callback, I think that part of the route/url is refered to as hash fragment. Altough if you are using hashHistory you need to use some tricks since you cannot have multiple fragments.

**Comment by maxmantz** [comment]
The parameter is called `url` in the oidc-client library. It makes sense both ways. When using react-router, you register routes as URIs, so I guess the naming is still accurate. Plus you also have to provide a route parameter to the middleware creator which is basically the same thing. 

Thanks for your thoughts. I'm also not using hash history, which isn't recommended anyways. I just hope this works for those who still use it :)

I'll close this for now.
