### ISSUE TITLE
[Question] USER_FOUND called to early?

### ISSUE THREAD

**Issue by AndreSteenbergen** [maxmantz/redux-oidc#141]
I am building an impersonate function. It basically takes an already logged in user and I login again, with acr_values set to the user I want to impersonate. This works fine, I set an extra claim on the identity server. However the redux-oidc state doesn't pick up on that. I logged all events, and added a console log when success callback is reached as well.

![afbeelding](https://user-images.githubusercontent.com/7676790/51559942-92907300-1e83-11e9-85ad-3448dee07fa0.png)

The first USER_FOUND event does not provide the Impersonating profile claim. In the success callback I do the following:

```
class CallbackPage extends Component {

  successCallback = (user) => {
    // get the user's previous location, passed during signinRedirect()
    console.log(["CALLBACK", user.profile]);
    var redirectPath = user.state.path;
    this.props.dispatch(userFound(user));
    this.props.dispatch(push(redirectPath));
  }
```
At this point in time I do have the updated claims in the profile. Is there a correct way to handle a relogin, with a different claims set the second time I login. The usermanager seems to pick up the extra claim, but the state uses the old user details.

I relogin as following (I am adding the displayname into the claim as well, so I don't need to get the full account as I mostly just need the name):

```
impersonateUser = () => {
    userManager.signinRedirect({
      data: { path: window.location.pathname },
      acr_values: `impersonatedUserId:${this.props.match.params.userId};${encodeURI(this.state.user.displayName)}`
    });
  }
```

**Comment by AndreSteenbergen** [comment]
It works but I do think this is strange ... It looks like the first USER_FOUND is incomplete (or cached) and after callback it is correct. I wouldn't mind a manual retrieval of the profile. I wouldn't know how to do that from the example app.

**Comment by maxmantz** [comment]
Hi,

if I understand your scenario correctly, you have two authentication requests, one for the initial login, the second for the impersonation. I never had this use case, so this is intriguing. Do you use the same CallbackComponent for both requests?

I don't see how USER_FOUND could be at fault here, it basically just puts the passed in user object into the reducer state. 

Something that could happen though is that the userManager itself passes the not-updated user object into the `successCallback` function.

My suggestion is to try
```
userManager.getUser().then(user => dispatch(userFound(user)); 
```
to see if this gets you the correct user object,

**Comment by AndreSteenbergen** [comment]
Hi, the calls are actually not that close together.

1. log in
2. get all users in system
3. select user
4. call impersonation (basically a simple login, with an extra acr_value)
5. server side the extra claim is added to the user, and a succes callback is given

My question regarding too soon with regard USER_FOUND is more it is being raised before the successCallback, when I don't manually raise the USER_FOUND myself the claims for the initial login remain present, not the claims from the second login.

**Comment by maxmantz** [comment]
I understand the question, however how and when the userManager fires the event is outside of our control. Anyways, your solution is totally fine and suitable for this situation.

**Comment by AndreSteenbergen** [comment]
Thanks for the feedback.
