### ISSUE TITLE
oidc object in store always missing

### ISSUE THREAD

**Issue by FreBon** [maxmantz/redux-oidc#142]
Hi,

Thanks for a great library! I never got the login flow to work so quickly with other libraries on other platforms :). But I have a problem.. I can't get the loged in user. The callback gets called and the user object looks good but when I'm trying to get the oidc.user obejct from state it's always null. I also tried to call the userManager.getUser(), but this one also returns null. So i Guess I'm missing some thing. 

This is how i set up the Store:
![image](https://user-images.githubusercontent.com/3351808/53157029-f1e7bd00-35c0-11e9-9a9d-4c9cc2dad4aa.png)

This is how i trigger the login:
![image](https://user-images.githubusercontent.com/3351808/53157071-075ce700-35c1-11e9-8c37-02391c7fa11a.png)

Callback:
![image](https://user-images.githubusercontent.com/3351808/53157120-2196c500-35c1-11e9-9fd0-5cf38aa1ae0f.png)

And in mapStateToProps the state.oidc is always undefined:
![image](https://user-images.githubusercontent.com/3351808/53157215-5145cd00-35c1-11e9-8341-b546d8dcbdce.png)

**Comment by maxmantz** [comment]
Hi!

Many thanks for the kind words. At first glance I can see that the CallbackComponent is not registered to any route.

Try the following: 
```
<Switch>
  <Route path="/" component={App} />
  <Route path="/callback" component={CallbackComponent} /> // <-- the path has to be the same as the one registered with your auth server
</Switch>
```

If you are using a dedicated login page like in the example app, you have to make a check whether or not the routes should be rendered. The check usually returns `true` when either a valid user is present, or the callback route has been requested. The code for this check in the example app is [here](https://github.com/maxmantz/redux-oidc-example/blob/master/src/components/homePage.js#L9).

Hope this helps!

**Comment by FreBon** [comment]
Thanks for the quick response :), I have the routing in another file so the callback works. I have a login component that I want to use to render login/logout buttons and the name of the currently logged in user etc. 

I'm triggering the login by clicking the login button that calls "userManager.signinRedirect" And in the callback i get the user:
![image](https://user-images.githubusercontent.com/3351808/53169260-06d24980-35dd-11e9-893c-9b6fc6363b52.png)



When i then try to get the user in a component the state.oidc is always undefined:
![image](https://user-images.githubusercontent.com/3351808/53168839-e48bfc00-35db-11e9-87d5-e45a67948d55.png)

So the question is how do i get hold of the logged in user in react?

**Comment by maxmantz** [comment]
Hard to tell from the information given. Is it possible for you to log the dispatched actions in the console? The `userManager` should dispatch the `USER_FOUND` action after a successful callback. If this doesn't happen, maybe the problem is there.

Also your last log message says that  `state.oidc` is `undefined`. Maybe something went wrong accessing the OIDC state in `mapStateToProps`?

**Comment by FreBon** [comment]
Hi, I figured out what the problem was.. I'm quite new to React/Redux and I didn't add the oidcReducer to my store. Since we are using react-redux-form this is what I ended up with:
![image](https://user-images.githubusercontent.com/3351808/53226569-c07ff780-367b-11e9-9a3b-3155cb33c1de.png)

![image](https://user-images.githubusercontent.com/3351808/53226622-ed340f00-367b-11e9-9529-5cdf5ede4f12.png)

**Comment by maxmantz** [comment]
Glad to see it's working now.
