### ISSUE TITLE
[Question] weird behavior with wrong system Time defined on client

### ISSUE THREAD

**Issue by RomainWilbert** [maxmantz/redux-oidc#147]
Hi !

I had issues connecting to my oidc server (IS4) : read web client app using redux-oidc acted like user was not connected even if I was correctly logged on IS4.

OIDC workflow went fine but session storage was empty (no token).

After investigating we found that the time was not property configured on the client side computer. 

I don't get why it caused issues with the library, I guess it has to do with the state / nonce control checks but as they are unaltered by the server, can you point out what in the library could cause this ?

Thanks

**Comment by maxmantz** [comment]
Hi!

This seems related to [oidc-client](https://github.com/IdentityModel/oidc-client-js). If your issue persists, please consider raising an issue there.
