### ISSUE TITLE
[Question] PKCE flow

### ISSUE THREAD

**Issue by danrday** [maxmantz/redux-oidc#148]
Hi! This library looks great but does it only allow for implicit flow? Is there a way to make this work with a PKCE code flow? Thanks!

**Comment by FuturistiCoder** [comment]
Hello @danrday,
Just change the `response_type` to `code` from your `UserManagerSettings`.

**Comment by maxmantz** [comment]
@danrday did @FuturistiCoder answer your question?

**Comment by danrday** [comment]
@maxmantz I ended up using AppAuth-Js for PKCE flow even though its documentation was very confusing and hard to implement. Thank you @FuturistiCoder  for your suggestion. :)
