### ISSUE TITLE
[Question] Can this be used as Single Sign-on?

### ISSUE THREAD

**Issue by janhartmann** [maxmantz/redux-oidc#15]
Hi.

This looks like an interesting library for something I am working on. 

I currently have a `oauth.myserver.com` which is a Identity Server 4 service. I am currently working on implementing a single sign on service on `login.myserver.com` which would be a pure React application which would communicate with my `oauth.myserver.com`.

Would this libray be able to aid me in this? I was thinking of letting my client application, e.g. `manager.myserver.com` redirect to `login.myserver.com` if the user is not logged in, then log in, and then redirect the user back to `manager.myserver.com` with the token?

**Comment by maxmantz** [comment]
Hi,

this package is agnostic to the signin method used with oidc-client & IdentityServer4, so I guess SSO should work (haven't tried it myself). This will likely involve certain configurations of the oidc-client package & IdentityServer4 so you should look there for further assistance on how to implement SSO.

**Comment by janhartmann** [comment]
Alright, I'll keep researching - thanks :-)
