### ISSUE TITLE
How to use with HashHistory?

### ISSUE THREAD

**Issue by acpower7** [maxmantz/redux-oidc#16]
In the example given, BrowserHistory is used, which assumes some server side configuration. I need to use HashHistory, however this method does not work and I get a blank page with the callback and id_token etc in the hash URL. Please advise on what I need to do differently when using react routers HashHistory.

**Comment by maxmantz** [comment]
I've tried recreating the issue with the example app using hashHistory. The problem I face is that Google OpenID doesn't allow hashes to be part of a valid callback URL. So I can't fully test this without setting up a custom OpenID provider.

There are however a few resources on this available. I've found issues regarding callback hashes with other users of the IdentityServer3 library (which is a customizable OpenID provider):
- [1](https://github.com/IdentityServer/IdentityServer3/issues/751)
- [2](https://github.com/IdentityServer/IdentityServer3/issues/1281)

From what I gather it is possible to get it working - if you have control over the authentication on the server side (by using something like IdentityServer). However, when you're trying to use a third party provider, such as Google's OpenID which doesn't allow hashes in the callback URL, you're out of luck.

I refer you to the issues I've linked for your research and close this issue as this is beyond the scope of this package.

Good luck!

**Comment by acpower7** [comment]
Thanks for that information. One more question, are there any plans to upgrade this library to React Router v4?

**Comment by maxmantz** [comment]
This library isn't dependent on react-router or any other routing library. You can use whatever router you want with it.

As for the example app, react-router v4 is still in alpha. I might upgrade it when it reaches a stable API, but have no plans for doing that just yet.

**Comment by maxmantz** [comment]
URL hashes are not supported. Please use browser history wherever possible,
