### ISSUE TITLE
"expires_at" not working properly

### ISSUE THREAD

**Issue by tech-gurgaon** [maxmantz/redux-oidc#162]
In LocalStorage,
Calculation of "expires_at" based on the "expires_in" is not calculating properly.

In oidc-client.min.js

line no 7999
this.expires_in == 7074
o.expires_in == 7199

Line no 1417
e.expires_in == 6795
and, here they are fixing "this.expires_at == wrong time"

**Comment by maxmantz** [comment]
This appears to be related to oidc-client. Please contact oidc-client if you need assistance.
