### ISSUE TITLE
immutablejs,optional dependency is bundled EVEN if reducer-immutable IS NOT used!

### ISSUE THREAD

**Issue by salvoravida** [maxmantz/redux-oidc#164]
Hi,
i think that immutable.js should moved to peerDep beacouse with optionDend it is included even if
reducer-immutable is NOT used.

i have dicover this with -> webpack-bundle-analyzer

**Comment by salvoravida** [comment]
or maybe an build ES6 is needed

**Comment by maxmantz** [comment]
fixed in version 3.1.6.
Thanks!
