### ISSUE TITLE
endsession trigger authorize

### ISSUE THREAD

**Issue by attiqeurrehman** [maxmantz/redux-oidc#167]
Hi,

I am facing an issue similar to [this](https://github.com/maxmantz/redux-oidc/issues/80#issuecomment-470700295) where `signoutRedirect `is calling the _/authorize_ endpoint instead of the _/endsession_ one. It seems like an event is fired by the `OidcProvider `that triggers the login before the logout finish.

Following is my config:

```js
const userManagerConfig = {
  client_id: 'web.dev',
  client_secret: 'secret',
  redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
  response_type: 'id_token token',
  scope: 'openid email profile role',
  authority: 'http://localhost:8080',
  silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew.html`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true
};
```

Here's the screenshot of the calls:

<img width="913" alt="cancells" src="https://user-images.githubusercontent.com/1382615/71582202-59d43180-2b09-11ea-8a5b-1535b6a5fcf2.PNG">

Thanks,
Attiqe

**Comment by attiqeurrehman** [comment]
I figured out the problem was on Login page it was calling `userManager.signinRedirect()` on `componentDidMount` so I changed the code with the following:

```
componentDidMount() {
    const {
      user,
      isLoadingUser
    } = this.props;

    if (!user && isLoadingUser) {
      userManager.signinRedirect();
    }
  }
```

I faced this issue because our requirement was to redirect to the login screen after logging out and if you have different scenario where you are going to the sigin on button click and then you might not face this issue.

**Comment by damien7792** [comment]
> I figured out the problem was on Login page it was calling `userManager.signinRedirect()` on `componentDidMount` so I changed the code with the following:
> 
> ```
> componentDidMount() {
>     const {
>       user,
>       isLoadingUser
>     } = this.props;
> 
>     if (!user && isLoadingUser) {
>       userManager.signinRedirect();
>     }
>   }
> ```
> 
> I faced this issue because our requirement was to redirect to the login screen after logging out and if you have different scenario where you are going to the sigin on button click and then you might not face this issue.

I'm facing the same issue, and I believe for the same reason as yours.
What are you passing to your component to populate "isLoadingUser"?

Thanks
Damien

**Comment by attiqeurrehman** [comment]
@damien7792 sorry for late reply. Following is the code for **isLoadingUser**:

```js
function mapStateToProps(state) {
  return {
    user: state.oidc.user,
    isLoadingUser: state.oidc.isLoadingUser
  };
}
```

**Comment by damien7792** [comment]
> @damien7792 sorry for late reply. Following is the code for **isLoadingUser**:
> 
> ```js
> function mapStateToProps(state) {
>   return {
>     user: state.oidc.user,
>     isLoadingUser: state.oidc.isLoadingUser
>   };
> }
> ```

Thank you, it solved my issue!
