### ISSUE TITLE
user State is not getting maintained between browser tabs

### ISSUE THREAD

**Issue by Jaganprafful** [maxmantz/redux-oidc#178]
Using the example I have configured my userManger, store, and HomePage but the issue with private routing I have enabled it by adding an additional reducer. If the user is logged in one tab when trying to invoke another tab directly bypassing the URL path application is redirecting back to the login page instead it should go the specified path and also in the session storage user object is not getting persisted so I am unable to secure my app

Here is my store file
![image](https://user-images.githubusercontent.com/67191031/93104901-0e2fdb00-f6cc-11ea-9de7-ce87e4dc8953.png)

And added an additional reducer for managing the authenticated state

![image](https://user-images.githubusercontent.com/67191031/93105196-649d1980-f6cc-11ea-8ab0-5bc4aeab410a.png)

Here is my privaterouter.tsx which allows only authenticated users 

![image](https://user-images.githubusercontent.com/67191031/93105579-e12ff800-f6cc-11ea-88a5-995957ff39d8.png)

@maxmantz  Can you please help me out as the user state in the new tab is not loaded even the user is logged in another tab, couldn't figure out whats the root cause

**Comment by cwoolum** [comment]
`oidc-client-js` stores session information in session storage, not local storage. Session storage is per tab. This is an except from the `oidc-client-js` config documentation on how to use local storage.

```
userStore: (default: session storage): Storage object used to persist User for currently authenticated user. 
E.g. userStore: new WebStorageStateStore({ store: window.localStorage })
```

**Comment by Jaganprafful** [comment]
Thank you, now I am using localStorage for my user store that resolved my issue.
