### ISSUE TITLE
Google OAuth: Refresh token not present in token response

### ISSUE THREAD

**Issue by anto-pt** [maxmantz/redux-oidc#191]
Hi @maxmantz

I have already implemented Keycloak with redux-oidc. It works really well.
Now I'm trying with Google OAuth. I'm facing the following issues

1. Refresh token is not present in token response.
Google docs suggests to pass access_type=offline to get the refresh token. When I tried to pass that in userManagerConfig it's not passing as a param in token endpoint. Seems it's not a configurable thing in redux-oidc library as I checked the lib classes.
How to get the refresh token with Google OAuth in token response?

Someone suggest to pass offline_access in scope. But it's not a supported scope in Google. Any help would be appreciated.

2. Google OAuth expecting client_secret to get the token response along with authority and client_id. But I don't see that in your example. Not sure how that works for you.

3. Access token couldn't be used for getting resource from API since it's not a JWT token. I can able use only id_token. Is this okay?

4. End_session_endpoint is not available in Google OAuth well known configurations. So I'm getting end session endpoint missing error while logout.

Appreciate your inputs on this. Mainly I need inputs on [1] Refresh token from Google

**Comment by maxmantz** [comment]
Hi,

a refresh token (or offline access type) is not supported by a client side javascript app, like a react app. Therefore no refresh tokens can and will be issued.

**Comment by anto-pt** [comment]
@maxmantz But for silent renew as well we need a refresh token to renew and get the token response right? This is what I observed when I worked with Keycloak. It has a refresh token and it was used to do userManager.signInSilent(). 

For Google OAuth as well if we pass the access_type=offline, it provides the refresh token.
https://accounts.google.com/o/oauth2/v2/auth?.......&**access_type=offline**

I have checked that with the [Google OAuth2 Playground](https://developers.google.com/oauthplayground/).

I'm still trying to figure out how to intercept these calls and pass the access_type=offline param in /auth call for Google. Any ideas would be appreciated.

**Note:**
My react application should be capable of configure any OAuth2 Authorization server (Keycloak, AWS Congnito, Okta.. (or) Any social login) with automatic silent renew support.

**Comment by maxmantz** [comment]
The way the refresh of tokens works in this library is that oidc-client registers an iframe on the site and a timer for the duration of the access token validity. When the token is about to expire, a new token is created via the iframe. No refresh token is needed.

**Comment by anto-pt** [comment]
Okay thanks for the explanation.

I need the following clarifications as well in general.

1. There is no end_session_endpoint available in Google OAuth in Google's well known configurations. So I'm getting end session **endpoint missing error** while logout.

So I just catch the error on userManager.signinSilent() and redirected the user to login. Is there any session maintained on Google OAuth server, if so how to clear that as well?

2. Google OAuth expecting client_secret to get the token response along with authority and client_id. But I don't see that in your example. Not sure how that works for you.

3. Access token couldn't be used for getting resource from API since it's not a JWT token. I can able use only id_token. Is this okay?

**Comment by anto-pt** [comment]
@maxmantz I'm getting this error on console while silent renew is about is about to happen (at the end of 1 hour access token life). Any idea on how to solve this?

Refused to display 'https://accounts.google.com/' in a frame because it set 'X-Frame-Options' to 'deny'.


{type: "redux-oidc/SILENT_RENEW_ERROR", payload: **Error: Frame window timed out**
    at t [as _error] (http://localhost:3000/static/js/1.chunk.js:2186…}
payload: Error: Frame window timed out at t [as _error] (http://localhost:3000/static/js/1.chunk.js:218628:55) at t [as _timeout] (http://localhost:3000/static/js/1.chunk.js:218634:51)
message: "Frame window timed out"
stack: "Error: Frame window timed out\n    at t [as _error] (http://localhost:3000/static/js/1.chunk.js:218628:55)\n    at t [as _timeout] (http://localhost:3000/static/js/1.chunk.js:218634:51)"
__proto__: Object
type: "redux-oidc/SILENT_RENEW_ERROR"
__proto__: Object

**Comment by anto-pt** [comment]
@maxmantz I just noticed that the Keycloak's well-know configuration has the **check_session_iframe**
`"check_session_iframe": "http://localhost:8090/auth/realms/titaniam-demo-app/protocol/openid-connect/login-status-iframe.html",`

But Google's well-known configuration doesn't have check_session_iframe. Does this makes any issue on the silent renew (Window timedout).
Because silent renew works fine with Keycloak but not with Google. 

**Note:**
I have seen your replies on the [issue-48](https://github.com/maxmantz/redux-oidc/issues/48) regarding iframe timeout/silent renew
I have implemented using a /silentRenew route and with silentRenewComponent. Unlike handling with a separate silent.html from your example app. I don't think this makes an issue on window timeout since silent renew works fine with Keycloak.

Kindly provide your inputs on this.

**Comment by anto-pt** [comment]
**Fixed the frame window timed out issue:**

**For Google OAuth:**

I missed adding the /silentRenew as Authorized redirect URIs in Google Developer console.
After added the /silentRenew window frame timeout issue went away

1. Go to https://console.cloud.google.com/apis/credentials
2. Click your oauth client you have created under OAuth 2.0 Client IDs
3. Add the following in Authorized redirect URIs
http://localhost:3000/
http://localhost:3000/callback
http://localhost:3000/silentRenew
