### ISSUE TITLE
Map UserLoggedOut to action

### ISSUE THREAD

**Issue by anderskristiansen** [maxmantz/redux-oidc#20]
Hi!

We are working on single sign out across browser tabs for all our clients that are using our OP. To achieve this we need to catch the `UserSignedOut` event which is fired if the session check fails. It would be nice if you could dispatch an action a registering a UserSignedOut event.  See [oidc.client.js](https://github.com/IdentityModel/oidc-client-js/blob/6a1f7ad5e48933777f1f49a23cbd3e2c8162c2b6/src/UserManagerEvents.js#L57)

Regards,
Anders

**Comment by maxmantz** [comment]
Agreed. Will add this as Sooners as I find Theo Time for it.

**Comment by maxmantz** [comment]
I've just pushed v2.2.2-beta.1 to npm. Please check it out and see if this helps you.

**Comment by anderskristiansen** [comment]
Hi!

Thanks for the quick response and fix. The event works as expected :)

**Comment by maxmantz** [comment]
Glad to hear it.
