### ISSUE TITLE
How is this possible that the app keeps state?

### ISSUE THREAD

**Issue by Sotorin** [maxmantz/redux-oidc#22]
I've been playing with some examples (redux-oidc-examples) and I can't figure out how is that possible that the app somehow keeps state on refresh. Once I logged on I hit the refresh button and I'm still on the same page. This is really good and may help my use case tremendously once I understand how this is done. On refresh, I'd expect the store and state be destroyed and app would go back to its default state of 'please login with google'.

**Comment by maxmantz** [comment]
The `userManager` stores the user in the storage passed in via it's settings. The middleware then checks on startup whether or not the user is present in said storage and passes it in to the reducer if it finds it. Look out for dispatches of `redux-oidc/USER_FOUND` during startup.

**Comment by Sotorin** [comment]
Got it. This makes sense. Thanks for your explanation.

**Comment by maxmantz** [comment]
Happy to help.
