### ISSUE TITLE
React Native - undefined is not an object

### ISSUE THREAD

**Issue by MyGuySi** [maxmantz/redux-oidc#24]
Hi, I'm trying to implement redux-oidc in React Native but I'm getting this error when importing `userManager.js`, any help would be much appreciated :)

```
undefined is not an object (evaluating 'r.TYPED_ARRAY_SUPPORT')
```

![img_0314](https://cloud.githubusercontent.com/assets/12952977/22111966/3cfd6ee6-de59-11e6-95a9-84061fcdb6fa.PNG)

**Comment by maxmantz** [comment]
The error message suggests an error in the oidc-client library. Unfortinately I cannot say for certain what exactly the cause is. Could be linked to [this](https://github.com/IdentityModel/oidc-client-js/issues/243) issue.

**Comment by MyGuySi** [comment]
Hm not sure, I'll take a better look tomorrow.

I see v3 has better support for react native, I thought it might be an
issue you may have encountered.

Are you able to successfully using redux-oidc with RN?

**Comment by maxmantz** [comment]
There are still issues to be resolved with react-native on oidc-client's side. We are in the process of finding those out and fixing them.

**Comment by MyGuySi** [comment]
No problem, I'll raise this issue on the oidc-client repo
