### ISSUE TITLE
Integration with react-native

### ISSUE THREAD

**Issue by maxmantz** [maxmantz/redux-oidc#25]
This package is built to support react-native. Due to my lack of experience with react-native I'm opening this issue to summarize the findings by users of this library.

**Comment by MyGuySi** [comment]
I'm putting together an example repo that should be helpful

**Comment by MyGuySi** [comment]
Haven't finished yet but may have found a potential issue. The CallbackComponent in redux-oidc calls `this.props.userManager.signinRedirectCallback()` on `componentDidMount()` with no params. `signinRedirectCallback()` can take a `url` param or will grab it from somewhere else.

https://github.com/IdentityModel/oidc-client-js/blob/1966f008330d3ea05357274466cf8092537d1415/src/UserManager.js#L232-L234

Like I said, I haven't really gotten that far yet but just something I noticed. We'll probably have to grab the url from the deep link callback and pass that along.

**Comment by maxmantz** [comment]
The url used by default is the redirect url passed into the userManger's settings. I have dropped the binding for this prop, but can reintroduce it if it is required. But I guess defining the URL once in the user manager's settings should be fine.

**Comment by MyGuySi** [comment]
I probably haven't dug far enough yet and I'm not super experienced reading other people's code so this is all a bit new to me! But how does the userManager get the tokens from the callback redirect?

**Comment by maxmantz** [comment]
No offense intended. 

The callback from the authentication server contains the token embedded in the URL of the callback with a hash. It looks just like this:

https://yoururl.com/callback#state=blob&access_token=blob&authuser=0&session_state=blob2&prompt=none

The user manager then fetches the token from the redirect callback.

**Comment by MyGuySi** [comment]
Oh sorry, I took no offense, should have included the emoji sooner hah.

Yeah ok that's what I thought. So will we have to pass that in manually from the deep link? The native app has no concept of a browser or way to get the url other than through the deep link callback

**Comment by MyGuySi** [comment]
Ok, I've put up my [Example](https://github.com/MyGuySi/ReactNativeOidcExample) repo but I'm getting this error:

`babelHelpers.typeof is not a function. (In 'babelHelpers.typeof(exports)', 'babelHelpers.typeof' is undefined)`

![simulator screen shot 20 jan 2017 13 33 00](https://cloud.githubusercontent.com/assets/12952977/22151209/fa0500ba-df14-11e6-88c7-d2f16e7e43b1.png)

**Comment by maxmantz** [comment]
Thank you for pushing your repo. I'll have a look at it as soon as I find the time. Maybe [this](http://stackoverflow.com/questions/35563025/new-react-native-app-has-typeerror-babelhelpers-typeof-is-not-a-function-ios) is related to your issue?

**Comment by MyGuySi** [comment]
Yeah I found that but adding react-native-stage-0 didn't seem to fix it... I'll probably take a good look after the weekend now, too intense for a Friday afternoon 😄

**Comment by MyGuySi** [comment]
I've looked into that error today. There is a fix in 0.41 but that's obviously not officially released yet.

The commit links to the same StackOverflow link that you suggested as a temp fix but I've added `react-native-stage-0` to .babelrc and I'm still getting the error.

**Comment by MyGuySi** [comment]
I think I'm going to build something for my application from scratch. It's going to take me a while to get up to speed with the way that `oidc-client` works and I don't really need all of the functionality that it provides initially. Hopefully I can build it out over time though and release it for others to use but it's not my priority right now. Feel free to get in touch if you need any RN help though.

**Comment by maxmantz** [comment]
@MyGuySi Thank you for your efforts. The difficulty I have right now is finding ways to register a callback for the RN app. Do you know how to do this or where I can look that up? I'm using Android.

**Comment by MyGuySi** [comment]
I've implemented mine just with HTTPS requests because it's our own identity provider, but you can use a custom URL and a deep link to get the callback 

https://facebook.github.io/react-native/docs/linking.html

**Comment by maxmantz** [comment]
That seems to be what I was looking for. Thanks again!

**Comment by sattaman** [comment]
Hi @maxmantz , I'm trying to implement oidc-client in react native too. I'm wondering whether it will be possible to use a [WebView ](https://facebook.github.io/react-native/docs/webview.html) for the login page, as that should mean we can refresh the token silently. I didnt realise the client wasnt tied to a browser until this morning so I'd been trying to do it manually.

**Comment by maxmantz** [comment]
Yes the WebView looks like the perfect fit for both login and silent renew. I would preferrably have it loaded at the root component (invisible or with 0 height & width) of the app. Then, when the `userManager` fires the `userExpiring` event, load up the required HTML file into it and have it silently renew the token. 

I would use another WebView to display the login page when no user is present, or the user is invalid / expired etc.

This is all still theoretical though, since I haven't had the time to implement it myself, but I don't see why it wouldn't be working like that.

**Comment by sattaman** [comment]
![](https://d3uepj124s5rcx.cloudfront.net/items/2Z0Q1V2S1J2W2Z0h3E2p/Screen%20Shot%202017-04-04%20at%2017.03.36.png?v=27dff4c3)

**Comment by sattaman** [comment]
Ive just been trying to import your package into react native and I'm hitting errors.

To recreate

```
 npm install -g create-react-native-app
    create-react-native-app my-app
    cd my-app/
    npm i --save redux-oidc
```
add an import in App.js - `import 'redux-oidc'`

`npm start`

The first error can be bypassed by deleting the `.babelrc` file from the `node_modules/redux-oidc` folder

**Comment by sattaman** [comment]
![](https://d3uepj124s5rcx.cloudfront.net/items/1s0v1w3p1u361I0G022h/Image%202017-04-04%20at%205.26.58%20PM.png?v=66c89a7c)

**Comment by maxmantz** [comment]
I have now created my own react-native project and I'm getting the error from [this issue](https://github.com/IdentityModel/oidc-client-js/issues/247). There seems to be something awry with loading external modules in react-native.

The second error you're facing ('fs') seems to come from jsrasign's usage of it. jsrasign is a dependency of oidc-client. I hope that can be circumvented somehow, or this will be a problem with compatibility.

**Comment by sattaman** [comment]
I've now got oidc-client working with React Native :) 
(although no session montioring or background refresh)

The fs error was strange since I couldnt see that dependancy in there, and it works now for oidc-client. 

So far I've created a `PopupNavigator` and `RNStore` components which I'm passing in to override the defaults in `UserManagerSettings`.  I'm going to have a go at implementing these with a WebView and see if it works. I can then do a PR to add the components I've created to your repo if you like? There is of course a dependancy on React Native for these components, so I'm not sure how this would work in terms of adding a dependancy on your module for these?

**Comment by maxmantz** [comment]
Sounds amazing. I'd be very happy to see what you came up with.

**Comment by sattaman** [comment]
Just to keep you updated, I wont be able to work on this until next week , but should be able to get something done then. I was wondering if it should sit in a separate repo to avoid adding a peer dependency on React Native?

**Comment by maxmantz** [comment]
Don't worry about the timing - I don't have much time to get into react-native right now either :)

About the dependencies - if you think you need specific stuff from the react-native library, a separate repo should do the trick. I'm not opposed to that approach by any means. Thanks again!

**Comment by tibbus** [comment]
Do you guys have any updates on this ?

I'm struggling to make it work with react-native, I have tried also without libraries just with the WebViews and still having some issues reading some cookies.

**Comment by sattaman** [comment]
@tibbus What issues are you finding? I've got oidc-client working with React Native, although not fully tested on android yet.

**Comment by tibbus** [comment]
I made it work as well, 2 days ago when I posted I used a wrong token for the logout, but now login and logout works perfectly inside a WebView.

Also was confused about some cookies from the WebView, but everything is sorted now.

**Comment by Dygerati** [comment]
Does anyone have an example repo using react native as a reference? One was posted earlier by @MyGuySi  but it doesn't seem to exist anymore.

**Comment by Proyoyo** [comment]
@sattaman Do you have an example repo for using oidc-client with React Native?

**Comment by MyGuySi** [comment]
@Dygerati Yeah sorry I removed it as we've since changed the way we're handling our auth. We switched to the resource owner flow and I'm managing token expiration manually.

**Comment by keirk** [comment]
I've got the same point as @maxmantz with the 'Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined' red screen - I've tried setting a custom WebStateStore for both userStore and stateStore ... but no joy so far. If @sattaman has any guidance or an example repo - it would be really helpful. Thanks.

**Comment by sattaman** [comment]
Sorry for the late response.  I don't have an example repo. 

I think the 'TYPED_ARRAY_SUPPORT' error was occurring for me using yarn but not using npm i possibly?

I created a Navigator which I passed to oidc-client as follows 

```
class CustomNavigator {
  constructor({ onNavigate } = {}) {
    this.onNavigate = onNavigate
  }
  prepare(params) {
    this._promise = new Promise((resolve, reject) => {
      this._resolve = resolve;
      this._reject = reject;
    });
    return Promise.resolve({
      navigate: ({ url }) => {
        this.onNavigate(url);
        return this._promise;
      },
    });
  }
  callback(url, keepOpen, delimiter) {
    this._resolve && this._resolve({ url });
    return Promise.resolve();
  }
}
```

then passed as 

```
  popupNavigator: new OidcNavigator({
    onNavigate: (url) => {
      Linking.openURL(url);
    },
  })

```

My AsyncStorageStore was

```
import { AsyncStorage } from 'react-native';

export default class {
  set(key, value) {
    return AsyncStorage.setItem(key, JSON.stringify(value));
  }

  get(key) {
    return AsyncStorage.getItem(key).then((res) => {
      const value = JSON.parse(res);
      return value;
    });
  }

  remove(key) {
    return this.get(key).then(value =>
      AsyncStorage.removeItem(key).then(() => value));
  }

  getAllKeys() {
    return AsyncStorage.getAllKeys();
  }
}

```

and this was set as 


```
  userStore: new AsyncStorageStore(),
  stateStore: new AsyncStorageStore(),
```

I did get it working with a WebView, but abandoned this as we are using Google as a provider and they block WebViews. I will be updating to use Chrome Custom Tabs https://github.com/droibit/react-native-custom-tabs or similar and sfsafariviewcontroller https://github.com/skycocker/react-native-sfsafariviewcontroller soon. Ill try and post a more complete solution soon

**Comment by NerdySaiyan** [comment]
I have created an example repo here: https://github.com/NerdySaiyan/redux-oidc-example-react-native

Thank you @sattaman for the code samples!

**Comment by maxmantz** [comment]
Amazing. Thank you! I'll check it out.

**Comment by rajeshrthl** [comment]
Hi @sattama, @NerdySaiyan 

Thank you very much for the explanation and example repo...
Can you please provide a complete example repo with customtabs, safariviewcontroller and silent signin implementation.

**Comment by maxmantz** [comment]
The implicit flow is not meant to be used by mobile devices - [this spec] should be used instead.

[This library](https://github.com/FormidableLabs/react-native-app-auth) implements this spec for react-native.

Therefore redux-oidc is not meant to be used with react-native. Closing this issue as a result. Thanks to everyone who helped in this thread and tried to make it possible.
