### ISSUE TITLE
USER_EXPIRED and LOADING_USER action fired every second

### ISSUE THREAD

**Issue by skolmer** [maxmantz/redux-oidc#30]
If the silent renew fails the application gets in a loop of executing USER_EXPIRED and LOADING_USER actions

**Comment by maxmantz** [comment]
I've published v3.0.0-beta.4 which addresses this issue. Please check it out and see if it fixes your issue.

**Comment by skolmer** [comment]
I cannot reproduce the error anymore. Thank you very much.
