### ISSUE TITLE
Clear user state if silent renew fails

### ISSUE THREAD

**Issue by skolmer** [maxmantz/redux-oidc#31]
Is it somehow possible to remove the user object from redux state if a silent renew fails?

**Comment by maxmantz** [comment]
Right now the reducer doesn't clear the user object. Assuming that shortly after silent renew fails, the user is expired, it would make sense for it to be cleared. I'll look into it.

**Comment by maxmantz** [comment]
Change implemented in v3.0.0-beta.5

**Comment by skolmer** [comment]
Thank you 👍
