### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by phrazed** [maxmantz/redux-oidc#32]
Hi, I'm getting this error everytime I try to use redux-oidc. I've added it to the entry in the webpack.config.js and also imported it in the entry to my app. Any idea?

**Comment by maxmantz** [comment]
Yes. You need to include teh [babel-polyfill(https://babeljs.io/docs/usage/polyfill/) in your build configuration.

**Comment by phrazed** [comment]
Yes, I've got that right I think. Don't worry, noone else has had this issue. It will be something silly on my end

**Comment by maxmantz** [comment]
The babel-polyfill is a strange beast. You either need to have it in your webpack entry like in the [example-app](https://github.com/maxmantz/redux-oidc-example/blob/master/webpack.config.js#L8) or import it once using an ES6 import statement in your `index.js`. I know that I had my issues with this. Best of luck :-).

**Comment by maxmantz** [comment]
Were you able to solve this issue?

**Comment by phrazed** [comment]
Yes, sorry. I wasn't sure of the protocol for closing the issue

**Comment by maxmantz** [comment]
No problem :)

**Comment by roblapp** [comment]
How did you resolve this? I have added an import statement to my index.js but am still getting the error.

**Comment by maxmantz** [comment]
You have to do one of the following:

Add an import statement to `index.js` like this:

`import 'babel-polyfill';`

OR

add it to your webpack config entry file like in the [example app](https://github.com/maxmantz/redux-oidc-example/blob/master/webpack.config.js#L8).

Hope this helps,

**Comment by roblapp** [comment]
I couldn't get it to work until I made 

`import 'babel-polyfill';`

the first import statement in the file. I had to use the import statement because I cannot easily modify my webpack.config file as I am using a [seed project from Facebook](https://github.com/facebookincubator/create-react-app) that essentially abstracts all configuration from the developer.

To be clear I will provide the exact code I use in my application's entry point...


```
import 'babel-polyfill';
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { OidcProvider } from 'redux-oidc';
import configureStore from './store/configureStore';
import userManager from './config/UserManager';
import AppRouter from './routes';
import './index.css';

const store = configureStore();

ReactDOM.render(
  <Provider store={store}>
      <OidcProvider store={store} userManager={userManager}>
        <AppRouter />
      </OidcProvider>
    </Provider>,
  document.getElementById('root')
);
```
