### ISSUE TITLE
Request to /.well-known/openid-configuration/jwks going to HTTP rather than HTTPS

### ISSUE THREAD

**Issue by shujaat-ali** [maxmantz/redux-oidc#35]
Hi there,

I tried to find solution for this within other issues but I couldn't. Please if it's duplicate route me to appropriate issue #.

Solution works fine locally as well as on server without HTTPS, but when I deployed this solution on test servers that require all requests to go over HTTPS I get the below pasted error when after login request comes back to callback component to load the user state.

Here is the error:
Mixed Content: The page at 'https://<clienturl>/callback#id_token=<idtoken>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<identityserverurl>/.well-known/openid-configuration/jwks'. This request has been blocked; the content must be served over HTTPS.

To me it seems when callback component originates XHR request for ".well-known/openid-configuration/jwks" it sends over HTTP rather than HTTPS. I have tried to pass jwks_uri with https to user manager setting but still same issue, it's not using the url that I pass.

I'd appreciate any help.

**Comment by maxmantz** [comment]
The error message describes what's wrong: Your OpenID-Connect authentication server is not served via HTTPS, while your app is under HTTPS. You'll have to use SSL with your OpenID-Connect authentication server as well for this to work.

**Comment by shujaat-ali** [comment]
Thanks for reply, really appreciate it. 

Okay, here is our setup. We use F5 Load Balancer which sits in between request and hosted apps. We have an iRule on F5 that redirects all HTTP requests to HTTPS. But when we pass on requests from F5 to apps hosted on IIS we send through HTTP. And most of our apps are hosted over HTTP within IIS, and so these two as well.

What I see in this case is that openid-configuration endpoints returns issuer/jwks_uri URLs with HTTP and when using these HTTP URLs userManager through XHR call tries to pull jwks endpoint content which itself is being served over HTTPS throw this error.

I'm correctly passing jwks_uri with HTTPS within userManager setting but my passed on values are not gettign effect. I'm passing jwks_uri: `https://......../.well-known/openid-configuration/jwks`,
  
The alternate option which you mention would you be elaborate it more for me.

**Comment by maxmantz** [comment]
What I meant was not to pass the jwks URL into the settings, but the JSON payload that the jwks endpoint gives out. Apologies for being unclear here.

Check out oidc-client's [wiki](https://github.com/IdentityModel/oidc-client-js/wiki#configuration) for details on how to do this.

**Comment by shujaat-ali** [comment]
Thanks for the directions. I think I'm making progress, now as per wiki I'm filling in metadata and signingKeys in settings (pasted below my sample code), and the mixed content error is gone. But now I'm getting ajavascript error "a.filter is not a function" in callbackcomponent. Any insights? 

const userManagerConfig = {
    client_id: '{client-id}',
    redirect_uri: `${HOST_URL}/callback`,
    response_type: 'id_token token',
    scope: 'openid profile ...',
    authority: AUTHENTICATIONSRV_URL,
    post_logout_redirect_uri: `${HOST_URL}/logout`,
    loadUserInfo: false,
    metadata: {
        issuer: `${AUTHENTICATIONSRV_URL}`,
        jwks_uri: `${AUTHENTICATIONSRV_URL}/.well-known/openid-configuration/jwks`,
        end_session_endpoint: `${AUTHENTICATIONSRV_URL}/connect/endsession`,
        authorization_endpoint: `${AUTHENTICATIONSRV_URL}/connect/authorize`
    },
    signingKeys: `${SIGNING_KEYS}`
};

**Comment by maxmantz** [comment]
Nope sorry - it seems to be a oidc-client issue. Maybe an object which is supposed to be an array? What does `${SIGNING_KEYS}` resolve to?

**Comment by shujaat-ali** [comment]
It seems signinRedirectCallback() is throwing this error.

${SIGNING_KEYS} is the static string contains the output from endpoint ${AUTHENTICATIONSRV_URL}/.well-known/openid-configuration/jwks which is .... {"keys":[{"kty":"RSA","use":"sig","kid":"00DB....."}]

**Comment by maxmantz** [comment]
Since `filter` is an array function, my guess is oidc-client wants only the value of the `"keys"` property.

**Comment by maxmantz** [comment]
This really is an oidc-client issue. I can only make guesses as to what is the problem and what can solve it. Please direct your question to oidc-client, where you will get better help.

**Comment by shujaat-ali** [comment]
Ok, passing a properly parsed JSON structure to signing keys worked for me. Below is my final version for setting. 
    const userManagerConfig_prod = {
        client_id: '{CLIENT_ID}',
        redirect_uri: `${HOST_URL}/callback`,
        response_type: 'id_token token',
        scope: 'openid profile ...',
        authority: AUTHENTICATIONSRV_URL,
        post_logout_redirect_uri: `${HOST_URL}/logout`,
        loadUserInfo: false,
        metadata: {
            issuer: AUTHENTICATIONSRV_URL,
            jwks_uri: `${AUTHENTICATIONSRV_URL}/.well-known/openid-configuration/jwks`,
            end_session_endpoint: `${AUTHENTICATIONSRV_URL}/connect/endsession`,
            authorization_endpoint: `${AUTHENTICATIONSRV_URL}/connect/authorize`
        },
        signingKeys: JSON.parse(SIGNING_KEYS)
    };

Thank you for your help and quick replies!

**Comment by maxmantz** [comment]
Happy to help :-)

**Comment by Navedac** [comment]
Hello.
I have the same problem.
Have you a step by step solution ?

**Comment by rosdi** [comment]
This works... thanks @shujaat-ali for sharing the settings.
I had to add "userinfo_endpoint" though otherwise userinfo won't get loaded... here is my final version:

var idServerUrl = "http://id-test.10.14.74.180.nip.io/";
var myClientId = "js_client";
var signingKeys = get signingKeys from idServerUrl + "/.well-known/openid-configuration/jwks".keys

var config = {
    authority: idServerUrl,  
    client_id: myClientId,
    redirect_uri: "http://localhost:3000/callback.html",
    response_type: "id_token token",
    scope: "openid profile email phone",
    post_logout_redirect_uri: "http://localhost:3000",
    silent_redirect_uri: 'http://localhost:3000/silent-renew.html',
    automaticSilentRenew: false,
    filterProtocolClaims: false,
    metadata: {
        issuer: idServerUrl,
        jwks_uri: idServerUrl + "/.well-known/openid-configuration/jwks",
        end_session_endpoint: idServerUrl + "/connect/endsession",
        authorization_endpoint: idServerUrl + "/connect/authorize",
        userinfo_endpoint: idServerUrl + "/connect/userinfo",
    },
    signingKeys: JSON.parse(signingKeys)
};
