### ISSUE TITLE
redux-oidc middleware catches all unhandled exceptions

### ISSUE THREAD

**Issue by ca0abinary** [maxmantz/redux-oidc#36]
Great work on the project! The only issue I'm having is that all my thrown errors seem to get caught by the middleware and presented (incorrectly) as oidc middleware errors. I think the issue is coming from this line:

https://github.com/maxmantz/redux-oidc/blob/b8f7f7b371c1e447f80857d01d1435b4e0a3bc17/src/oidcMiddleware.js#L50

What do you think? Is there a way to have my own code's exceptions bubble to the top without getting caught?

**Comment by maxmantz** [comment]
This is a "bug" in a sense that the error messages are indeed unclear. The only alternative I can think of is dropping the `catch` part of the middleware. I will look into this.

**Comment by maxmantz** [comment]
Fixed in v3.0.0-beta.6
