### ISSUE TITLE
How can I make the silent_renew works with create-react-app?

### ISSUE THREAD

**Issue by thangchung** [maxmantz/redux-oidc#41]
Sorry for my stupid question, but at the moment I use the redux-oidc lib with the famous [create-react-app](https://github.com/facebookincubator/create-react-app) starter kit from the React team. I integrate the app with [IdentityServer4](https://github.com/IdentityServer/IdentityServer4). I can log in, log out normally, but only one thing I could not make it work is silent_renew because the create-react-app doesn't allow us to add another files i.e silent_renew.html and index.js (like in the [redux-oidc-example](https://github.com/maxmantz/redux-oidc-example) repo). My question is how can we make it work in this case?

**Comment by maxmantz** [comment]
Hi there! I'm sorry, I'm not familiar with create-react-app or how its internal configurations work. The example app does it by adding a second entry point to the webpack config. Is there really no way to access this in create-react-app? Maybe your question is best asked at the create-react-app repo.

**Comment by HermannHH** [comment]
@thangchung were you able to solve this problem for create-react-app? I have the same problem and not sure how to get it working.

**Comment by thangchung** [comment]
@maxmantz Thanks for your reply. @HermannHH  I am still finding the solution for that :(

**Comment by HermannHH** [comment]
Please let me know if you do @thangchung . I will do the same. PS. I have added a S/O question here: http://stackoverflow.com/questions/43938570/adding-silent-renew-entry-point-to-reactcreate-react-app

**Comment by maxmantz** [comment]
As this question has been answeren on StackOverflow, I will close this issue now. Thank you @HermannHH & @thangchung for your efforts in resolving this.
