### ISSUE TITLE
Uncaught Error: You must provide a user manager!

### ISSUE THREAD

**Issue by OscarCanek** [maxmantz/redux-oidc#42]
I've been trying the library for a couple of days but when a I run the app I always got the message: "Uncaught Error: You must provide a user manager!" but my user manager is defined 'cause when I print the object and is not undefined nor null. 

The error is triggered in the component `<OidcProvider store={store} userManager={userManager}>`.

What am I doing wrong?

**Comment by maxmantz** [comment]
The `OidcProvider` isn't throwing the error message - though maybe it should...
The error message comes from [the middleware](https://github.com/maxmantz/redux-oidc/blob/master/src/oidcMiddleware.js#L41). Please make sure you pass it into the `createOidcMiddleware(userManager)` function.

**Comment by OscarCanek** [comment]
It works now, I think it was a problem of dependencies versions. I have another question: What is a silent renew?. I'm using create-react-app, Could you tell me how to add it to my app?

**Comment by maxmantz** [comment]
Silent renew is the automatic renewal of the access token when it expires. Integration with create-react-app is proving to be difficult because of the restrictions this repo has towards custom configuration. Please see [this issue](https://github.com/maxmantz/redux-oidc/issues/41) for further details.

**Comment by maroparo** [comment]
Still receiving this error even though I've passed the userManager to createOidcMiddlweare ... Any idea why this might be happening ?
