### ISSUE TITLE
prop-types warnings on v2.2.1

### ISSUE THREAD

**Issue by DinerIsmail** [maxmantz/redux-oidc#44]
Since updating to React v15.5 I keep getting warnings about prop-types being used from React.PropTypes. I've traced the warnings as coming from redux-oidc. Would you be able to release a v2 that fixes that?
If you can point me to a branch for v2 I can submit a PR for that myself, but I can't see one.

**Comment by maxmantz** [comment]
This has been fixed in the latest beta of version 3 by externalizing React's `prop-types`. Please understand that version 2 is no longer being actively maintained. Please upgrade to version 3 for these warnings to disappear.

**Comment by DinerIsmail** [comment]
@maxmantz I've tried updating to that and it breaks the authentication on our app. I've just blamed that on the fact that it's a beta version, so will be waiting for a more stable version. Thanks!

**Comment by maxmantz** [comment]
Interesting. What errors are you getting? The beta is stable as to my knowledge. Reporting any errors you encounter has the benefit of me fixing them or helping you to resolve them...

**Comment by DinerIsmail** [comment]
I get this:
```
app.js:5514 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `r`, expected a single ReactElement.
    in r (created by OpenIdCallback)
    in OpenIdCallback (created by Connect(OpenIdCallback))
    in Connect(OpenIdCallback) (created by RouterContext)
    in main (created by App)
```

**Comment by olavhaugen** [comment]
I just added a pull request https://github.com/maxmantz/redux-oidc/pull/49, fixing this issue along with another warning about react-test-utils.
