### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by stjepan** [maxmantz/redux-oidc#46]
Hi,

I have ejected (after no luck without) a create-react-app (1.3.1 with react-scripts (1.0.7) to try to resolve the issue. Following dependencies are added afterwards:
```
"dependencies": {
    "babel-polyfill": "^6.23.0",
    "co": "^4.6.0",
    "oidc-client": "^1.3.0",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-oidc": "^3.0.0-beta.7"
  }
```
Starting index.js is updated accordingly (store is created as by ex. from react-redux, userManager is created as by ex. from redux-iodc-example; this is just to have a valid store for Provider /OidcProvider and userManager for OidcProvider):
```
import 'babel-polyfill';

import React from 'react';
import ReactDOM from 'react-dom';
import { createStore } from 'redux';
import { Provider } from 'react-redux';
import { OidcProvider } from 'redux-oidc';
import { createUserManager } from 'redux-oidc';

import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './index.css';

function todos(state = [], action) {
  switch (action.type) {
    case 'ADD_TODO':
      return state.concat([ action.text ])
    default:
      return state
  }
}

let store = createStore(todos, [ 'Use Redux' ]);

const userManagerConfig = {
  client_id: '581912277515-8pqeloei552og7pa13iufb57iug8vu9k.apps.googleusercontent.com',
  redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
  response_type: 'token id_token',
  scope: 'openid profile https://www.googleapis.com/auth/youtube.readonly',
  authority: 'https://accounts.google.com',
  silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew.html`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true,
};

const userManager = createUserManager(userManagerConfig);

ReactDOM.render(
    <Provider store={store}>
        <OidcProvider store={store} userManager={userManager}>
            <App />
        </OidcProvider>
    </Provider>,
    document.getElementById('root')
);
registerServiceWorker();
```
As you can see, I've made sure babel-polyfill is included before anything else. I did some googling and found [this](https://medium.com/@jcse/clearing-up-the-babel-6-ecosystem-c7678a314bf3) (old, but might be valid) comparisation/explanation between [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) and [babel-runtime](http://babeljs.io/docs/plugins/transform-runtime/) (which is added as devDependency by create-react-app). I also tried the setup as described on babel-runtime (with .babelrc) without luck.

I also tried explicitly adding regeneratorRuntime without luck (babel-runtime/regenerator is actually using regenerator-runtime inbehind), as following:
```
import regeneratorRuntime from "regenerator-runtime";
```
Any workaround suggestion?

Thanks!

**Comment by stjepan** [comment]
The only way I got it working is to import it as following:
import 'babel-polyfill/dist/polyfill.js';

**Comment by adamjcsmith** [comment]
I had imported this at the top of my file:
```jsx
import 'regenerator-runtime/runtime';
```
But still a 'regeneratorRuntime is undefined' error. Adding this line underneath fixed my issue:
```jsx
import 'babel-polyfill/dist/polyfill.js';
```
