### ISSUE TITLE
Why second HTML file for the silent renewal?

### ISSUE THREAD

**Issue by AlexDee-SP** [maxmantz/redux-oidc#48]
Hello! Thanks for the package!!

I didn't find the answer in the documentation so I wonder why do we need to have a second HTML file for the _Silent renew_ feature. 

I have React application with a single HTML file and registered route for the silent renewal (routing is done using _react-router_). With this setup I'm able to perform a token renewal ~~at least one time.
 For some reason the second time, when application renews a token, I get _SILENT_RENEW_ERROR_ with message saying _Frame window timed out_. I wonder if this issue is related with having only one HTML file.~~

Thank you!

**Update** I've changed the _accessTokenExpiringNotificationTime_ and set it to 58 minutes (having a token with 1 hour expiration interval). After this change my application successfully renews token every 2 minutes without any timeout errors. So, I guess, the question about  _Frame window timed out_ should be asked in _oidc-client-js_ repo issue tracker.

 Could you then answer my first question about the need of having separate HTML file for silent renewal. Is anything wrong with having a single file? Thank you again!

**Comment by AlexDee-SP** [comment]
Any comments are greatly appreciated!

**Comment by maxmantz** [comment]
The second HTML file is required by `oidc-client` for silently renewing the token. The `userManager` opens up an iFrame where this second HTML file is loaded into. It then executes the token renewal. I hope this helps.

**Comment by AlexDee-SP** [comment]
This means that it's only a matter of performance then: to load a separate HTML file with minimum code into the iFrame to perform the _silence renew_ or to load the main single HTML file with all assets. Both ways should work and, besides the timing and performance differences, there are no issues.
Am I right?

**Comment by maxmantz** [comment]
I don't know what you are trying to do. All I know is that oidc-client needs this second HTML file for the iFrame.

**Comment by AlexDee-SP** [comment]
Hm... I read all available docs for the _oids-client_ but didn't find a word about the second HTML file. The only thing they're talking about is the _silent_redirect_uri_ (I'm so sorry if I'm wrong in this case and please point me to the place at their Wiki where it talks about the second HTML file). 

That brings me to the point where I believe that the _second HTML_ requirement comes from the _redux-oidc_ package, and I wonder about the reasoning. At the end of the day my question is "Is it OK to serve the _silent_redirect_uri_ from the same HTML file from the _redux-oidc_ point of view? If response is negative, then Why?"

**Comment by maxmantz** [comment]
Have you looked at the [samples](https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample-silent.html)?

**Comment by AlexDee-SP** [comment]
Thanks for the link! As you can see in the [examples,](https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample.js) they use separate HTML file for every route. I believe the reason behind it is that they don't mess with the routers in the examples (because showing the router work isn't the point of the example).

Regarding the redirect I would say, that I do see the redirect page when user initially signs in. But later I definitely don't see the redirect page (and even any sort of flashing in the browser) when the silent renew happens, all this work is happening in the background, I see only requests in the Network inspector. And the reason of me not seeing the redirect page on the silent renew is because it is all (request and further redirect) happening in the iFrame, isn't it?

If I'm not missing anything, then the only reason using the second HTML file for the silent renew is  minimizing its size and time of loading it into the iFrame. With one single HTML file silent renew works as well, but in this case a larger file is loaded into the iFrame which can potentially cause _window timeout_ errors (as larger file takes more time to be loaded into the iFrame).

**Comment by AlexDee-SP** [comment]
Thanks for the link! As I can see in the [examples,](https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample.js) they use separate HTML file for every route. I believe the reason behind it is that they don't mess with the routers in the examples (because showing the router work isn't the point of the example).

Regarding the redirect I would say, that I do see the redirect page when user **initially** signs in. But later I definitely don't see the redirect page (and even any sort of flashing in the browser) when the silent renew happens, all this work is happening in the background, and I see only requests in the Network inspector. And the reason of me not seeing the redirect page on the silent renew is that it is all (request and further redirect) happening in the iFrame, isn't it?

If I'm not missing anything, then the only reason of using the second HTML file for the silent renew is the minimizing its size and time of loading it into the iFrame. With one single HTML file silent renew works as well, but in this case a larger file is loaded into the iFrame which can potentially cause _window timeout_ errors (as larger file takes more time to be loaded into the iFrame).

**Comment by anto-pt** [comment]
I am also getting the **window timeout errors** while silent renew happens, when the access token lifetime is 1 hour. I'm also using a single HTML file in react and manager /silentRenew route with silent renew component. 

@AlexDee-SP  Do we really a separate html file for this? I'm trying to solve the window timeout with Google OAuth
