### ISSUE TITLE
Redux-Oidc with Isomorphic react-app

### ISSUE THREAD

**Issue by Shadowman4205** [maxmantz/redux-oidc#51]
Hello, any suggestion/example how i can use this package with isomorfpic react application?

**Comment by TesloCosmin** [comment]
Same question here. I tried using it with .NET Core 2.0 (preview 2-006497) in VS 2017 15.3 (Preview 2) on React.Redux template, but it throws error:

```
redux-oidc.js?96a5:1 Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at Object.defineProperty.value (redux-oidc.js?96a5:1)
```
It says there it needs babel-polyfill but I don't know how to configure it in this wepback configuration the template came with.

Any help is greatly appreciated.

**Comment by maxmantz** [comment]
Usually the babel-polyfill can be installed via an entry point in the webpack config or by simply adding

`import 'babel-polyfill'` in your index.js

**Comment by maxmantz** [comment]
Closing this.
