### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by YellowSmiley** [maxmantz/redux-oidc#56]
Both a colleague and I have tried merging your example into our app to get the Oauth token we need to make API calls using our SSO and both of us got stuck on the callback component when it tries to:

    this.props.dispatch(push('/'));

... In the successCallback. I guess this is a common issue seeing as we both had it? Any help? We've been stuck on this for days!

**Comment by maxmantz** [comment]
`push` is a funciton by react-router-redux. Are you using and importing it correctly?

**Comment by YellowSmiley** [comment]
It was imported correctly but still returning an error - I implemented redux-oidc into a create-react-app however when I migrated the content from the create-react-app into your example using plain webpack, it seems to work. However I am struggling to get the webpack to build CSS now... If anyone has this problem I suggest doing it this way (bit long winded but at least it works).
