### ISSUE TITLE
Automatic sign in callback

### ISSUE THREAD

**Issue by PeterKottas** [maxmantz/redux-oidc#58]
Hi there.
First of all, how the hell this only has 71 stars? You need to popularize this a bit. I would hate see this fall into abyss without community support. It's really useful and neatly done piece of code.

Secondly and the actual issue or more of a question if you will:
My app uses automatic sign in as it's a dashboard and therefore requires user acc at all times. 
I was curious what would you recommend to make this happen properly. Right now I have 
```typescript
if (this.props.location && this.props.location.pathname != '/callback') {
    userManager.getUser().then(response => {
    if (!response) {
      userManager.signinRedirect();
    }
  });
}
``` 
Which looks a bit dodgy imho. Is there a better practice?

Secondly, is there some sort of callback that is triggered after user logs in?
I need this for some authenticated api calls. I am getting the access_token from the redux state so it would need to be populated by then. 
I was trying to place that logic into previous if. But that won't get triggered this is in componentDidMount and redirect from callback will only pass in new props. Basically something that is called after redux-oidc/USER_FOUND

Hope it makes sense. Help appreciated. Cheers

**Comment by maxmantz** [comment]
Hi!

Thank you for your kind words :)

Your approach by using pathname is actually almost the same that I use in my react apps when it comes to user detection and it works like a charm 👍. It might look dodgy, but it is simple and efficient.

There is only one thing I would add: I would check for the `expired` flag the userManager gives the user when the token has expired. So it would look like this: 

```
if (this.props.location && this.props.location.pathname != '/callback') {
    userManager.getUser().then(response => {
    if (!response || response.expired) {  // <==
      userManager.signinRedirect();
    }
  });
}
```
This implementation will always redirect to the server when no valid user is present or the access token is expired. I *strongly* recommend also implementing silent renew of the access token with this setup, as without it it will terminate the app regularly to make the roundtrip to the identity provider, because access tokens commonly have short lifetimes.

**Comment by PeterKottas** [comment]
Awesome! Glad to see my setup makes sense. Yep I already have silent renew and it works like a charm. As a sidenote, does it use refresh tokens? I think it might not as I am not sure it that's doable with implicit flow, just asking.
Also what about the logged in callback? What would you recommend there?

**Comment by maxmantz** [comment]
No it doesn't use refresh tokens. It basically requests a new token just like it did the first time around when it was triggered by the check to pathname in your code example. Because the user has already authenticated the client app before, the identity provider can remember this and just give out another token.

What you do with your logged in callback is up to you. Nothing is required. What I do though is to check for the route the user has requested. For example if the redirect was triggered on route `/my/awesome/route` I call:

```
const state = {
  path: window.location.pathname
};

userManager.signinRedirect(state);
```

The user object returned then has a `session_state` attribute which you can use to redirect you user to the route he has requested, like this: 
```
signinCallback = (user) => {
  this.props.dispatch(user.session_state.path); // should redirect to /my/awesome/route
}
```

**Comment by PeterKottas** [comment]
Again, very clever. The only problem is it doesn't work :D 
I do the thing you proposed, the state on passing into the signinRedirect is correct. 
However, when I do 

```typescript
    private successCallback(user) {
        console.log(user);
        this.props.navigateTo(user.session_state.path);
    }

    public render() {
        return <CallbackComponent userManager={userManager} successCallback={this.successCallback.bind(this)} errorCallback={this.successCallback.bind(this)}>
            <div>Redirecting...</div>
        </CallbackComponent>;
    }
```
I get
```typescript
session_state : "sH9VIxml94s5CCWoOestWulcp5CX-eUSHpVp6cakXUs.ca7f45318ee546fb487a17e8652122f2"
state : undefined
```
I managed to solve my need of where to put the initialization code, can be useful for somebody else. This is what I do now for actions that fires after user logs in:
```typescript
public componentWillReceiveProps(newProps: LayoutProps){
    if(!this.props.oidc.user && newProps.oidc.user){
            this.props.getRoles();
        }
    }
```
Again, might not be the cleanest of codes but it works and it's a single place where I put this so I am happy.

**Comment by maxmantz** [comment]
My bad, I posted it wrong. The argument to siginRedirect must be an object like this.

```
userManager.signinRedirect({
  data: {
    path: window.location.pathname
  }
});
```

**Comment by PeterKottas** [comment]
Spot on, plus one minor thing
```typescript
    private successCallback(user) {
        console.log(user);
        this.props.navigateTo(user.session_state.path);
    }
```
Becomes
```typescript
    private successCallback(user) {
        this.props.navigateTo(user.state.path);
    }
```

Sidenote, I really wish more people see this lib. One thing I did in past for my [dot net core win service lib](https://github.com/PeterKottas/DotNetCore.WindowsService) is just google for various keywords find forums that mentioned the topic my lib deals with, and paste non spamy answer. I know stars are superficial but github gives you more traffic if it's popular and this should be! Gl and thanks a lot mate!

**Comment by maxmantz** [comment]
Happy to help. And thank you again :-)

**Comment by BartoGabriel** [comment]
First of all, very good project.

This thread helped me a lot in my project, since it is an application that only serves for logged in users.

I think this would be good if it is in the documentation or in the examples. Or at least leave a link to this issue.

With all the information provided, I made a component that verifies if the user started or not session, if it is not valid, it redirects to the login, and if it is valid it renders the application's views.

Also implement the Callback as you described it.

I leave all the code in case someone can serve you:

```javascript
//CheckAuth.js
import { withRouter } from "react-router-dom";
import React from "react";
import userManager from "./userManager";

class CheckAuth extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isValidUser: false
    };
  }

  componentDidMount() {
    if (this.props.location && this.props.location.pathname !== "/callback") {
      userManager.getUser().then(response => {
        if (!response || response.expired) {
          userManager.signinRedirect({
            data: {
              path: window.location.pathname
            }
          });
        } else {
          this.setState({
            isValidUser: true
          });
        }
      });
    } else {
      this.setState({
        isValidUser: true
      });
    }
  }

  render() {
    const { isValidUser } = this.state;
    if (!isValidUser) {
      return <div>Loading...</div>;
    } else {
      return this.props.children;
    }
  }
}

export default withRouter(CheckAuth);
```

```javascript
//CallbackPage.js
import React from "react";
import { CallbackComponent } from "redux-oidc";
import userManager from "../userManager";

const successCallback = (user, history) => {
  history.push(user.state.path);
};

const errorCallback = error => {
  console.error("errorCallback", error);
};

function CallbackPage(props) {
  return (
    <CallbackComponent
      userManager={userManager}
      successCallback={user => successCallback(user, props.history)}
      errorCallback={errorCallback}
    >
      <div>Redirecting...</div>
    </CallbackComponent>
  );
}

export default CallbackPage;
```

```javascript
function App() {
  return (
    <Router>
      <CheckAuth>
        <Layout>
          <Route exact path="/" component={Home} />
          <Route path="/test" component={Test} />
          <Route path="/callback" component={CallbackPage} />
        </Layout>
      </CheckAuth>
    </Router>
  );
}
```

Thank you very much for the explication

**Comment by damien7792** [comment]
Thank you all for this thread, very helpful.

I have a question for @BartoGabriel : how do you get the componentDidMount to trigger each time you navigate to a different screen? With the way I implemented it, componentDidMount triggers when the page is initially loaded, but then, never again.

For example, if I load the site with the homepage, which is unprotected, CheckAuth fires up and checks that the page is unprotected, and does nothing else. Then, I click on the link to a protected page: CheckAuth doesn't fire again, and I can access the page without being authenticated.

index.tsx
```
ReactDOM.render(
    <Provider store={store}>
        <OidcProvider store={store} userManager={userManager}>
            <ConnectedRouter history={history}>
                <App />
            </ConnectedRouter>
        </OidcProvider>
    </Provider>,
    document.getElementById('root'));
```

App.tsx
```
export default () => (
    <CheckAuth>
        <Layout>
            <Route exact path='/' component={Home} />
            <Route path='/counter' component={Counter} />
            <Route path='/callback' component={CallbackPage} />
            <Route path='/fetch-data/:startDateIndex?' component={FetchData} />
        </Layout>
    </CheckAuth>
);
```

CheckAuth.tsx
```
import { withRouter, RouteComponentProps } from "react-router-dom";
import * as React from "react";
import userManager from "./userManager";

type CheckAuthProps =
    RouteComponentProps<{}>;

type CheckAuthState =
    // Component's specific state
    {
        isValidUser: boolean
    };

class CheckAuth extends React.Component<CheckAuthProps, CheckAuthState> {
    constructor(props: CheckAuthProps) {
        super(props);
        this.state = {
            isValidUser: false
        };
    }

    componentDidMount() {
        console.log('CheckAuth');
        if (this.props.location && this.props.location.pathname !== "/" && this.props.location.pathname !== "/callback") {
            console.log('This path is protected:', this.props.location.pathname);
            userManager.getUser().then(response => {
                if (!response || response.expired) {
                    console.log('User not authenticated or expired. Response:', response);
                    userManager.signinRedirect({
                        data: {
                            path: window.location.pathname
                        }
                    });
                } else {
                    console.log('User authenticated. Response:', response);
                    this.setState({
                        isValidUser: true
                    });
                }
            });
        } else {
            console.log('This path is unprotected:', this.props.location.pathname);
            this.setState({
                isValidUser: true
            });
        }
    }

    render() {
        const { isValidUser } = this.state;
        if (!isValidUser) {
            return <div>Redirecting...</div>;
        } else {
            return this.props.children;
        }
    }
}

export default withRouter(CheckAuth);
```

Thanks

**Comment by BartoGabriel** [comment]
The **CheckAuth** component is used to know if a user has a valid session or not at the time the application is loaded (the component is not continually checking it). It is designed for different cases than the one you want to implement.

Basically:
1. A user enters.
2. Verify that the user has a valid session:
   * **IsValid == true**: Children are displayed. Then other components are in charge of keeping the session alive (silent refreshtoken, etc ...)
   * **IsValid == false** is redirected to the login
   * _While doing this work it shows a "Loading ..."_

Sorry for the delay in my response. I hope I've helped.
