### ISSUE TITLE
TypeScript definition included dependency on redux-actions

### ISSUE THREAD

**Issue by CHRISBRD** [maxmantz/redux-oidc#60]
Version: 3.0.0-beta.10

When compiling a TypeScript application that references this library - we receive the following error:
```
 ERROR in [at-loader] ./node_modules/redux-oidc/index.d.ts:3:40
          TS2307: Cannot find module 'redux-actions'.
```

This appears to be caused by the fact that the TypeScript definition file includes an import for 'redux-actions', yet 'redux-actions' is not listed as a dependency in `package.json`.

Two possible solutions would be to either add a dependency on 'redux-actions' to this library, or remove the references to it from the TypeScript definition file. We would be happy to submit a PR if you could indicate a preference.

**Comment by maxmantz** [comment]
I'm personally not using TypeScript so I don't have an opinion about how to approach this. If you want to submit a PR fixing this issue, you are more than welcome to do so :).
