### ISSUE TITLE
Token is not load when application start

### ISSUE THREAD

**Issue by danielmahadi** [maxmantz/redux-oidc#61]
Hi @maxmantz ,

Great work on the library.
I am having a small issue here in my code,

The app will start to fetch data (which require auth) from the server.
On the initial load, user will need to login and data will be loaded (all is good here),
but then when user refresh the browser, the fetch will get 401... but the flow is different, it will redirect to the identity server and then callback immediately without login page.

Then I investigate further and I realise that there is a race condition between redux-oidc try to load the user from localstorage and app try to fetch in initial load.

This is how the store is configured:
```
const oidcMiddleware = createOidcMiddleware(userManager);
const preloadState = {};
const store = createStore(
  rootReducer,
  preloadState,
  compose(
    applyMiddleware(thunk, oidcMiddleware)
    , window.devToolsExtension ? window.devToolsExtension() : (f) => f
  )
);
```

And the oidc options:
```
const opts = {
  client_id: "app1",
  redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
  response_type: "id_token token",
  scope: "openid profile somepermission",
  authority: "http://localhost:5000",
  silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew.html`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true,
  userStore: new WebStorageStateStore({ store: localStorage }) 
};

const userManager = createUserManager(opts);
```

How do you overcome this issue?

Any help will be appreciated. 😄 
Good day. 👍

**Comment by maxmantz** [comment]
Hi!
To overcome the race condition, I usually split my app into sections that are only available when the user is present or not.

For example when you have a component that renders data from an API request which needs a valid token, I render these components in a sub part of my app. Then I have a parent component which checks for a valid user and if a valid user is present, shows the components.

Like this:

```
render() {
  return this.props.user && !this.props.user.expired ? <MainContent /> : <LoginPage />;
}
```

Hope this helps.

**Comment by danielmahadi** [comment]
Hi @maxmantz 

Thanks for the help. 😄
