### ISSUE TITLE
No semver match for "oidc-client-fetch": ">=1.2.0" on NPM

### ISSUE THREAD

**Issue by spoldman** [maxmantz/redux-oidc#62]
When trying to install I always get the following error

 Couldn't find any versions for "oidc-client-fetch" that matches ">=1.2.0"

That is because only version available on NPM server is 1.2.2-fetch1 and that does not match ">=1.2.0"

**Comment by spoldman** [comment]
Just to add some context I'm trying to install using Lerna bootstrap command using yarn workspaces. 
For some reason it always tries to install optional dependencies even though I tell it not to.

**Comment by maxmantz** [comment]
Fixed in beta.12. Thanks for the report!
