### ISSUE TITLE
ID token in URL after callback

### ISSUE THREAD

**Issue by BrianMcRails** [maxmantz/redux-oidc#64]
Just a question not an issue, in my app after the user is authenticated and sent back through the callback component the 'callback/id_token' stays in the URL. I'm not doing anything out of the ordinary, but I can't figure out how to get it the URL back to the root.

The routing works perfectly fine. Let me know if you have any ideas, and awesome library thanks for creating and sharing!

**Comment by maxmantz** [comment]
Hi, and thanks for the kind words!

The `<CallbackComponent />` accepts a `successCallback` prop, which is normally used to redirect the user after a sucessful login. See [this line](https://github.com/maxmantz/redux-oidc-example/blob/master/src/components/callback/index.js#L8) in the example app.

**Comment by BrianMcRails** [comment]
Yep I am using the success callback exactly as described in the example and still seeing this. The redirect to home page works perfectly fine but the URL stays with the full ID token in it. Not sure if I'm just missing something basic, but I am actually just using an exact copy of the callback component in example.

**Comment by BrianMcRails** [comment]
May not even be related to the library but this is my first time working with oidc in a react project so I'm not sure where else to ask

**Comment by maxmantz** [comment]
I'm not sure then why this happens. Are you using react-router's hash history? This could cause issues.

**Comment by BrianMcRails** [comment]
Yeah I'm using the BrowserRouter, haven't had much success yet still but I will keep this question updated if I figure it out.

**Comment by BrianMcRails** [comment]
I was able to resolve by using the withRouter higher order component from react router dom then using this.props.history.push("/") in the '<successCallback>'
```javascript
import React from 'react';
import { connect } from 'react-redux';
import { CallbackComponent } from 'redux-oidc';
import userManager from '../../utils/userManager';
import { withRouter } from 'react-router-dom';

class CallbackPage extends React.Component {
    successCallback = () => {
        this.props.history.push("/");
    };

    render() {
        // just redirect to '/' in both cases
        return (
            <CallbackComponent userManager={userManager} successCallback={this.successCallback} errorCallback={this.successCallback}>
                <div>

                </div>
            </CallbackComponent>
        );
    }
}

function mapDispatchToProps(dispatch) {
    return {
        dispatch
    };
}

export default withRouter(connect(null, mapDispatchToProps)(CallbackPage));
```

**Comment by BrianMcRails** [comment]
Thanks for the help pointing me to router issue, appreciate your library!
