### ISSUE TITLE
Example with react and typescript

### ISSUE THREAD

**Issue by smairo** [maxmantz/redux-oidc#65]
Hi! Is there any examples using this with react with typescript (tsx) or how should i proceed if i wanted to implement this with them?

I'm using Microsoft.AspNetCore.SpaTemplates as a base, so if anyone has managed to implement this to react+redux template i'd really appreciate a hand here :)

**Comment by maxmantz** [comment]
Sorry, I don't use typescript. I don't know if anyone has done what you ask.

**Comment by ThunderDev1** [comment]
I have used this successfully with Typescript and the aspnet core react-redux template if you have any questions.

**Comment by meninjanho4788** [comment]
@ThunderDev1 can you share some code, how to setup this library with react + redux + netcore 2 or some suggestion.

**Comment by ThunderDev1** [comment]
I don't have any code I can share for now, but the setup is pretty straightforward. First you will need to setup [identity server](http://docs.identityserver.io/en/release/). They have very good documentation and complete samples using netcore 2 including an example using a javascript client. Create an Api project and configure it following the instruction in identity server docs. Create your Spa with react redux template, then just look at the redux-oidc sample app to see how to set it up.

**Comment by meninjanho4788** [comment]
thank you @ThunderDev1

**Comment by smdonoghue** [comment]
@ThunderDev1 I am going through the same process now of creating a React App from the React-Redux SPA template and trying to integrate this library in TypeScript. I've mostly got it in apart from the conversion of the CallbackPage.js component. Did you have any trouble with this? Can you share how you setup the component and the default export? Thanks.

**Comment by ThunderDev1** [comment]
Hi @smdonoghue what errors are you getting ? can you post your code ?

Here is what my CallbackPage.tsx looks like

```
import * as React from 'react';
import { connect } from 'react-redux';
import { CallbackComponent } from 'redux-oidc';
import { User } from 'oidc-client';
import { push } from 'react-router-redux';
import userManager from './../utils/userManager';
import { RouteComponentProps } from 'react-router';

type CallbackPageProps = RouteComponentProps<{}> & { dispatch: any }

class CallbackPage extends React.Component<CallbackPageProps, {}> {

   successCallback = (user: User) => {
    var redirectPath = user.state.path as string;
    this.props.dispatch(push(redirectPath));
  }

  errorCallback = (error: Error) => {
    this.props.dispatch(push('/'));
  }

  render() {
    return (
      <CallbackComponent 
        userManager={userManager}
        successCallback={this.successCallback}
        errorCallback={this.errorCallback}
      >
        <div className="loader"></div>
      </CallbackComponent>
    );
  }
}

export default connect()(CallbackPage) as typeof CallbackPage;
```
To get the redirect path to work you need to pass it when calling signinRedirect

`userManager.signinRedirect({ data: { path: window.location.pathname } });`

**Comment by smdonoghue** [comment]
Thanks for responding @ThunderDev1! 

For a start, I can see that your prop type (CallbackPageProps) for the React Component are being constructed differently to mine so I'll bring that inline with how yours is working and hopefully that should sort the issues I'm having out.

**Comment by smdonoghue** [comment]
@ThunderDev1 The Callback component compiles and is functioning now so thanks again for that!

One final thing, do you have to initiate the Oidc Client functions - like signinRedirect() etc - from within each component independtly or would you do this in a central location?

**Comment by smdonoghue** [comment]
Cool, that would be good to see and very helpful! Much appreciated.

In the meantime I'll take onboard your advice and extend the root component to perform some of authentication checks.

**Comment by ThunderDev1** [comment]
Here it is [https://github.com/ThunderDev1/reactjs-ts-identityserver](https://github.com/ThunderDev1/reactjs-ts-identityserver) :)

**Comment by smdonoghue** [comment]
Good work @ThunderDev1!

I'm sure there will be a few like me that could do with some guidance and find this a massive help.
