### ISSUE TITLE
Suggestion: Passing errorCallback as prop to CallbackComponent

### ISSUE THREAD

**Issue by lizter** [maxmantz/redux-oidc#7]
I was thinking, a lot can go wrong in the redirect road. States not matching, or even an exception. As for now, an error is thrown. How can I as a user of the library decide what to display to the user  in different error scenarios? Right now it logs to console and is plain stuck on the "Redirecting..." view.

Could a solution be to pass in an `errorCallback` as a property to the `CallbackComponent` to make it more flexible?

**Comment by maxmantz** [comment]
Good idea. I will look into it.

**Comment by maxmantz** [comment]
I have just released version `2.1.0-beta.1` with a few changes. `errorCallback` is now a prop for the `CallbackComponent`. It takes a function which gets the error passed in. Try it out and see if it works for you. 

`oidc-client` is now a peer dependency. You will have to install it manually by running `npm install oidc-client`.
