### ISSUE TITLE
Is middleware necessary?

### ISSUE THREAD

**Issue by NerdySaiyan** [maxmantz/redux-oidc#70]
To me it seems like the oidc-client library exposes all the necessary events to keep the redux state in sync. If the loadUser helper function is called in the componentWillMount method of OidcProvider, and the events keep redux state in sync, then what gap is the middleware filling? Why is it needed?

Great library! Thank you in advance!

**Comment by maxmantz** [comment]
Hi! The middleware is needed when you don't have silent renew set up because it checks the validity of the user object. If you have silent renew set up, you will not need it, because the access token will be automatically renewed before it expires.
