### ISSUE TITLE
Auto redirect to OIDC Provider

### ISSUE THREAD

**Issue by capiono** [maxmantz/redux-oidc#72]
I'm implementing authentication/authorization using redux-oidc for reactjs. I followed the implementation in the sample project.

```
const userManagerConfig = {
    client_id: 'portals',
    response_type: 'id_token token',
    scope: 'portalApi IdentityApi openid profile email offline_access',
    authority: 'http://localhost/authtest',
    filterProtocolClaims: true,
    loadUserInfo: true,
    accessTokenExpiringNotificationTime: 10,
    
    post_logout_redirect_uri: window.location.origin,

    redirect_uri: window.location.origin +  '/callback',

    automaticSilentRenew: true,
    silent_redirect_uri: window.location.origin + '/silent.html',
    
    revokeAccessTokenOnSignout: true,
  };
```

In my store my oidcmiddle ware is created like:

`const oidcMiddleware = createOidcMiddleware(userManager, () => true, true, '/callback');`

From the documentation, if triggerAuthFlow is set to true, the middleware triggers a redirect to the OpenID provider when the user is expired.
This is not happening.
Also, have registered the OidcProvider nested below react-redux's Provider:

```
<Provider store={store}>
    <OidcProvider store={store} userManager={userManager}>
        <ConnectedRouter history={history}>
            <App/>
        </ConnectedRouter>
    </OidcProvider>

```

Currently, when I load the application, the user state is always null. 
Without clicking a login button, how do I automating redirect to the OIDC provider (IdentityServer 4), if user is not authenticated or user state is null (SESSION EXPIRED)?

**Comment by maxmantz** [comment]
The wiki is for the previous version of this library. I've dropped `triggerAuthFlow` because it wrestled control away from the user and had side effects that were hard to manage. Now, if you want to automatically sign the user in you can do that by calling `userManager.signinRedirect()` after `SESSION_EXPIRED` is dispatched.

**Comment by capiono** [comment]
Thanks maxmantz. Is the this right way to call redirect:

I have a generator function:

```
export function * redirectToODICSaga() {
  yield take(USER_EXPIRED);
  userManager.signinRedirect();
 // yield put(loadingUser());
}
```

which I can in my store:

sagaMiddleware.run(redirectToODICSaga);

Which this the redirect gets called, but I'm new to reactjs and just want to verify I'm doing it the right way.

**Comment by maxmantz** [comment]
Yes, that would be the correct way to do it in a saga.

**Comment by capiono** [comment]
thanks.
