### ISSUE TITLE
Undefined user.state in callback

### ISSUE THREAD

**Issue by ccxiadev** [maxmantz/redux-oidc#74]
Hi,
    So here's our configuration 
```

const baseUrl = `${window.location.protocol}//${window.location.hostname}\
${window.location.port ? ':' + window.location.port : ''}/`

const userManagerConfig = {
  client_id: '',
  authority: '',
  redirect_uri: baseUrl + '#/callback',
  response_type: 'token id_token', // must be token id_token
  scope: 'openid profile email', // must be openid profile email
  loadUserInfo: false, // must be false
  automaticSilentRenew: true,
  silent_redirect_uri: baseUrl + 'oidc-silent-renew.html',

}

```

Callback setup 
```
const CallbackPage = ({ redirectToIndex }: Props) => {
  return (
    <CallbackComponent userManager={userManager} successCallback={redirectToIndex}>
      <div>
        Redirecting...
      </div>
    </CallbackComponent>
  )
}

const mapDispatchToProps = (dispatch: Dispatch<{ type: string }>) => {
  return {
    redirectToIndex: (user: User<*>) => {
      // Trying to get redirectUrl here but state is undefined
      dispatch(push(user.state.redirectUrl))
    },
  }
}

```
After callback, user.state is undefined. 

We are trying to follow [redux-oidc-example](https://github.com/maxmantz/redux-oidc-example). 
But the example doesn't seem to cover our use case.

**Comment by LoganBarnett** [comment]
I'm a colleague of @ccxiadev and wanted to point out our ultimate goal is to get the `redirectUrl` to be preserved as the browser bounces between our callback page and the OIDC provider. It seems like this was once covered via the middleware function, but from glazing over the current form of it in v3, it doesn't seem to support that functionality anymore.

We'll probably start a deep dive on this next week - any insights here would be much appreciated!

**Comment by maxmantz** [comment]
This is because the state has not been passed to the userManager. Try the follwing and see if it fixes your issue:

```
// the call to redicrect to the IdP
userManager.signinRedirect({
  data: { redirectUrl: window.location.pathname }
});
```
Then after the callback, the user object should have the `redirectUrl` set.

**Comment by ccxiadev** [comment]
@maxmantz That fixes our issue indeed! Thanks for the prompt response.

**Comment by jasonreact** [comment]
@maxmantz
We love this solution that you have provided, keep up the good work.

I am having a very similar issue to this because I am not sure where to put the solution that you mentioned above.  Any help that you can provide is much appreciated.  We love this solution that you have provided, keep up the good work.

Where are you recommending this be placed?

`userManager.signinRedirect({
  data: { redirectUrl: window.location.pathname }
});`

Does this go in the Callback code or prior to the callback?  Here is my Callback

`class LoginCallback extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        console.log("in callback props:", this.props);

        return (
            <CallbackComponent
                userManager={userManager}
                successCallback={() => this.props.dispatch(push('/landing'))}
                errorCallback={error => {
                    this.props.dispatch(push("/"));
                    console.error(error);
                }}
            >
                <div>Redirecting...</div>
            </CallbackComponent>
        );
    }
}

function mapDispatchToProps(dispatch) {
    return {
        dispatch
    };
}

export default connect(null, mapDispatchToProps)(LoginCallback);`
