### ISSUE TITLE
loadUser does not dispatch LOADING_USER action

### ISSUE THREAD

**Issue by rmkpatchaa** [maxmantz/redux-oidc#76]
When the **loadUser** function is called , the **LOADING_USER** action is not dispatched.
So the state value `isLoadingUser` is always false.

In my application, I have something like that : 
```js
function HomePage(props) {
  const { user, isLoadingUser } = props;

  if(isLoadingUser) {
    return <span>Loading...</span>
  }
  if(!user || user.expired) {
    userManaper.signinRedirect(); // This redirects to the login server 
                                                        // as I don't have an explicit login page
    return <span>Loading...</span>;
  }

  return <MainPage />;
}

function mapStateToProps(state) {
  return {
    user: state.oidc.user,
      isLoadingUser: state.oidc.isLoadingUser
  };
}
```
Every time the application is loaded, it redirects to the login server, as it does not have the information that the user is loading (via loadUser call).

**Comment by maxmantz** [comment]
You are correct, currently the loadUser helper is not dispatching the LOADING_USER action. I will add this to the next update.

**Comment by rmkpatchaa** [comment]
You can check the pull request #77 I have made.
It corrects this behavior and it works on my application.

**Comment by maxmantz** [comment]
The new version (beta.13) now dispatches `LOADING_USER`. I hope this fixes your issue. Thanks for the report.
