### ISSUE TITLE
Not getting access_token after the callback

### ISSUE THREAD

**Issue by bizarosteve** [maxmantz/redux-oidc#78]
We are using IdentityServer3 server for IdP, implicit flow, React/Redux application.

In render() for the Callback component (before returning &lt;CallbackComponent&gt;) this.props includes a location prop with access_token, expires_in, scope, state, and token_type values all set.  But in the successCallback  method on the same component the returned parameter (user) has an undefined access_token, although the expires_at, scope, and token_type values are set.  Any thoughts on what I can do to make sure the access_token is passed through, or to debug the issue.  Thanks for your help.

**Comment by maxmantz** [comment]
This shouldn't happen. Can you provide a sample to reproduce this issue? I suggest forking the example app and applying your IdentityServer settings to it. Maybe this helps in keying in on the issue.

**Comment by bizarosteve** [comment]
@maxmantz  thanks I will trying forking and applying my settings.
