### ISSUE TITLE
New app doesn't redirect to login page?

### ISSUE THREAD

**Issue by ashic** [maxmantz/redux-oidc#79]
I'm setting up a new project with this, and I can see redux-oidc/LOADING_USER is fired, followed by redux-oidc/USER_EXPIRED. However, nothing happens, and the user isn't redirected. How can I make it redirect to the identity provider when the user needs to log in? And if their login expires, how can I ensure they'll be redirected to the login page again?

My setup looks like:

```
const config = {
    client_id: '...',
    redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/callback`,
    response_type: 'id_token token',
    scope: 'openid profile',
    authority: 'http://localhost:4444/',
    post_logout_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/login`,
    silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/silent_renew.html`,
    automaticSilentRenew: true,
    filterProtocolClaims: true,
    loadUserInfo: true
}

// create a user manager instance
const userManager = createUserManager(config);

// create the middleware
const oidcMiddleware = createOidcMiddleware(userManager, () => true, true, '/callback');

```

**Comment by ashic** [comment]
I called ```userManager.signinRedirect()```, and it proceeds further. But there's now another problem; I'm getting a CORS error from the authority (which is ory/hydra). 

On another note, is it possible to make this work with the authorisation code flow instead of implicit flow?

**Comment by maxmantz** [comment]
Getting a CORS error hints at a problem with the IdP and is beyond this library to solve. 

For your second question - this library wraps oidc-client-js to be used with React/Redux. oidc-client-js is a library specific for the implicit flow, which is also the desired flow for client based applications. In other words, unless oidc-client-js makes changes to support authorisation code flow, this library will not support it.
