### ISSUE TITLE
Issues in `userManager.signoutRedirect();` - not logged out

### ISSUE THREAD

**Issue by IncRev-Bala** [maxmantz/redux-oidc#80]
@maxmantz I'm using `redux-oidc` in my react application to consume the Identity Server (Auth Service). I can't able to logout using `userManager`

**Code**: 

```
import { createUserManager } from 'redux-oidc';

const userManagerConfig = {
    authority: `https://localhost:5000/core`,
    client_id: 'Terminal',
    redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/callback`,
    post_logout_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,

    response_type: 'id_token token',
    scope: 'openid ilab',

    // silent renew will get a new access_token via an iframe
    // just prior to the old access_token expiring (60 seconds prior)
    silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/SilentRenew`,
    automaticSilentRenew: true,

    // will raise events for when user has performed a logout at IdentityServer
    monitorSession: true,

    // this will allow all the OIDC protocol claims to vbe visible in the window. normally a client app
    // wouldn't care about them or want them taking up space
    filterProtocolClaims: true,

    // this will use the user info endpoint if it's an OIDC request and there's an access_token
    loadUserInfo: true,

    acr_values: `tenant:bbm`
};

const userManager = createUserManager(userManagerConfig);

export default userManager;

```

If I use the above exported object `userManager` for logout its not working `userManager.signoutRedirect();` Its going to the Identity Server and return backs to the client application and loads the application in an old state (i.e., logged in state).

How to implement `userManager.signoutRedirect();` in Redux ReactJs.

**Comment by maxmantz** [comment]
Your settings look fine. Maybe some leftover state is still in your session storage after logout. Can you try to call `userManager.clearStaleState()` before the call to `signoutRedirect()` and see if this helps?

**Comment by maxmantz** [comment]
Were you able to fix this issue?

**Comment by gdubs** [comment]
I have the same issue. I tried this and the userManager.clearStaleState() and userManager.removeUser(); does not log out the user. Was wondering if the expected behavior is to redirect the user to the Identity server logout url? If so, is there another way where there would be no redirect to the Identity server url, just log out the user from both the usermanager memory and the identityserver ?

**Comment by Karillion** [comment]
Also seeing this issue on beta 16. Rolling back to beta 14 solves the problem.

**Comment by maxmantz** [comment]
`removeUser` will remove the user object from memory and log you out locally, `signoutRedirect` should redirect you to your IP and try to log out externally. If both don't work, something is wrong with your setup.

**Comment by yosbeleg89** [comment]
I'm having a case similar to this one, where the signoutRedirect is calling the `/authorize` endpoint instead of the `/endsession` one. It seems like an event is fired by the `OidcProvider` that triggers the login before the logout finish. @maxmantz any idea of what could be the issue? Thanks

**Comment by slemvs** [comment]
> I'm having a case similar to this one, where the signoutRedirect is calling the `/authorize` endpoint instead of the `/endsession` one. It seems like an event is fired by the `OidcProvider` that triggers the login before the logout finish. @maxmantz any idea of what could be the issue? Thanks

Could you tell us how you solved the problem, please?

**Comment by yosbeleg89** [comment]
@slemvs I resolved it calling `removeUser` before `signoutRedirect`, but also adding `id_token_hint` to the last one:

```TS
UserManager.removeUser().catch((reason) => {
      console.error(reason)
    })
UserManager.signoutRedirect({ id_token_hint: this.props.user && this.props.user.id_token }).catch((reason) => {
      console.error(reason)
    })
```

Check this other issue https://github.com/maxmantz/redux-oidc/issues/134
