### ISSUE TITLE
NPM dist package createUserManager problem

### ISSUE THREAD

**Issue by kudlacekv** [maxmantz/redux-oidc#85]
Hi,
when you look at compiled library in dist folder file redux-oidc.js (version from npm 3.0.0-beta.14) there is code for helper function createUserManager
```javascript
var o=void 0;
try{
	o=t(14).UserManager
}
catch(e) {
	try{
		o=t(!function(){var e=new Error('Cannot find module "oidc-client-fetch"');throw e.code="MODULE_NOT_FOUND",e}()).UserManager
	}
	catch(e) {
		throw new Error("redux-oidc: Couldn't find UserManager. Please install either 'oidc-client' or 'oidc-client-fetch'.")
	}
}
```

As you see this function never use oidc-client-fetch. Result of server side rendering is error "sessionStorage is not defined".

Workaround is easy just use new UserManager from correct package. But this function is used in all examples, so little hint "don't use with SSR" or something like that would be fine.

Anyway thank you for your work.

**Comment by maxmantz** [comment]
Thank you for your feedback. I will look into it.
