### ISSUE TITLE
Implement Silent Renew in Reduc OIDC

### ISSUE THREAD

**Issue by cstpraveen** [maxmantz/redux-oidc#86]
I've gone through silent renew and I've tried to implement silent renew method. I don't know how to implement. Please don't consider this as a silly question. I really need this.

```
const userManagerConfig = {
  client_id: process.env.REACT_APP_OAUTH_CLIENT_ID,
  post_logout_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}`,
  redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/oauth/callback`,
  silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}:${window.location.port}/silent_renew.html`,
  response_type: 'id_token',
  scope: process.env.REACT_APP_OAUTH_SCOPE,
  nonce: process.env.REACT_APP_OAUTH_NONCE,
  acr_values: process.env.REACT_APP_OAUTH_ACR,
  authority: process.env.REACT_APP_OAUTH_SERVER,
  automaticSilentRenew: true,
  loadUserInfo: true
};
```

In my another page
```
componentDidMount() {
        processSilentRenew()
}
```

**Comment by loliver** [comment]
I just implemented silent renew by [following the wiki](https://github.com/maxmantz/redux-oidc/wiki/4.-Silent-renew).

Simply added the 2 lines of code there in to my existing silent callback js file which is packed up in to a separate bundle by webpack.

**Comment by maxmantz** [comment]
No worries, I don't consider this a silly question. From your config everything looks fine. It seems like something is wrong with your webpack configuration. Please consult [this article](https://webpack.js.org/concepts/entry-points/#multi-page-application) in the webpack docs on how to achieve this, or check out the [example app's webpack config](https://github.com/maxmantz/redux-oidc-example/blob/master/webpack.config.js#L11).

**Comment by loliver** [comment]
Make sure your token issuer (backend) is supplying the `expires_in` param in the Location response header, I think that's on the `authentication` call. Sorry not at work so can't check our codebase.

**Comment by maxmantz** [comment]
Were you able to fix this?

**Comment by cstpraveen** [comment]
I've created a static file in public directory and run a added a below script 

`new Oidc.UserManager().signinSilentCallback();` 

which works fine.
