### ISSUE TITLE
Logging out in a React Application

### ISSUE THREAD

**Issue by LukeHardyLexacom** [maxmantz/redux-oidc#88]
Hi,
I have been having an issue with a logout scenario with our react application that we are building. I have come back to this issue a few times and searched online and cannot seem to see the same scenario anywhere.

The problem is: When I hit logout, the users state is removed which in turn instantly causes a react refresh and changes my navigation menu to the logged out version before the oidc has performed a redirect to the 'LoggedOut' page.

This is the navigation logged in/ logged out check:
```if (user && !user.expireduser) {```

This is my logout button:
```<MenuItem className="nav-buttons" primaryText={t('logoutText')} onClick={this.onLogoutButtonClicked} disabled={this.state.disabled} />```

And this is the supporting on click code:
```onLogoutButtonClicked() { this.setState({ disabled: true }); this.props.userManager.signoutRedirect(); }```

Previously, I was using the ```usermanager.RemoveUser();``` as per the examples in the documentation but this gave us the same behaviour. It would remove the user from the state, causing a react refresh of the navigation menu (while loading to redirect to 'are you sure you want to log out' page) before it would redirect to the loggedOut/logout page.

My question is, how can I assure that the user state remains until the signout has completed on the redirect 'You are now logged out' page. This way, my navigation menu would not change until the signout has completed and I wouldn't get this strange flash of menus before refresh.

The same thing happens when the page shows 'Redirecting...' after a login has happened because the user state has not updated to yet to have an active valid user. Is there a way that you can access these events happening while they are firing so that we can hook into it? Or am I using this all wrong?

Thanks.

**Comment by maxmantz** [comment]
Hi,

this is an interesting problem. The `signoutRedirect()` removes the user object from the reducer, so the 'menu flashing' is the result of intended behavior. There is no direct fix for this, but I suggest you can create a flag in your reducer, something like this:
```
// your reducer state
const state = {
 isLoggingOut: false
 // other props...
}
```

and have your logout button do something like this:
```
const onLogoutButtonClick = () => {
  dispatch({
    type: 'SET_IS_LOGGING_OUT',
    payload: true
  });

  userManager.signoutRedirect();
};
```

Then add this flag to the condition when you want to show your menus, something like this:
```
render() {
  const shouldShowMenus = this.props.user && !this.props.user.expired && !this.props.isLoggingOut;

  return shouldShowMenus ? <Menus /> : <LoginPage />;
}
```

Hope this helps!

**Comment by LukeHardyLexacom** [comment]
Hi @maxmantz 

Thanks for getting back to me, I am currently working on some other tasks but going to try this out ASAP.

We wanted to try and stay away from having to create a reducer and going this route but this seems like its the only option.

Will get back to you how I get on.

Thanks

**Comment by maxmantz** [comment]
Any updates on this?

**Comment by LukeHardyLexacom** [comment]
Working on this at the moment, will let you know asap

**Comment by LukeHardyLexacom** [comment]
We only currently import the oidc reducer like so:

`import { reducer } from 'redux-oidc';`

We then just combine that with our other reducers.

The way you suggest would mean that I would have to have a custom redux oidc reducer or am I missing something within the docs?

**Comment by maxmantz** [comment]
No, I'm suggesting setting a flag in another reducer.

**Comment by LukeHardyLexacom** [comment]
This is now implemented however, the user is removed from the state as soon as you hit Logout. So it ignores the check against the menu because at that point the user is undefined/null before the logout redirect happens.

**Comment by LukeHardyLexacom** [comment]
Okay I made a change to the check:

`user && !user.expireduser || this.props.isLoggingOut`

However you still get the page change because I believe the user is removed from state before the actual logout redirect happens?

**Comment by maxmantz** [comment]
The logout redirect happens immediately, but due to network lag it takes some time to materialize.

**Comment by LukeHardyLexacom** [comment]
I dont think we can get any closer with this, so what you have suggested before works well enough.

Thank you!
