### ISSUE TITLE
redux-oidc: Error loading user in oidcMiddleware: Object does not support property or method "from" in IE 11

### ISSUE THREAD

**Issue by drwatson1** [maxmantz/redux-oidc#89]
I tried to use oidc middleware as in an example. In Chrome, Edge and others all work fine but in IE 11 I get this error:

> redux-oidc: Error loading user in oidcMiddleware: Object does not support property or method "from"

If I use loadUser instead I get a similar error (in IE only):

> redux-oidc: Error loading user in loadUser: Object does not support property or method "from"

Should this work in IE (v11 would be enough)? Is there any workaround?
Please help, it is critical for me

**Comment by drwatson1** [comment]
Middleware:

```
import { createStore, applyMiddleware, compose } from 'redux';
import { browserHistory } from 'react-router';
import { routerMiddleware } from "react-router-redux";
import createOidcMiddleware from 'redux-oidc';
import calcApp from './reducers';
import thunkMiddleware from 'redux-thunk';
import { composeWithDevTools } from 'redux-devtools-extension';
import userManager from './oidc/userManager';

const oidcMiddleware = createOidcMiddleware(userManager);

const createStoreWithMiddleware = compose(
	composeWithDevTools(applyMiddleware(oidcMiddleware, routerMiddleware(browserHistory), thunkMiddleware)))(createStore);

const store = createStoreWithMiddleware(calcApp);
```

And configuration as this:

```
import { createUserManager } from 'redux-oidc';

const userManagerConfig = {
  client_id: 'clientid',
  redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
  response_type: 'token id_token',
  scope: 'openid profile api',
  authority: 'http://localhost:3002',
  silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew.html`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
	loadUserInfo: false
};

const userManager = createUserManager(userManagerConfig);
```

**Comment by drwatson1** [comment]
Sorry, it is not redux-oidc issue. I found the reason. IE does not have method Array.from used in oidc-client. After applying [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) all works fine.

**Comment by drwatson1** [comment]
Also, I found a strange behavior. Previously I had this CallbackPage implementation:

```javascript
class CallbackPage extends React.Component {
  onError = (err) => {
    // some code
    console.error(err);
  }
  render() {
    return (
      <CallbackComponent
        userManager={userManager}
        successCallback={() => this.props.dispatch(push("/"))}
        errorCallback={(err) => this.onError(err)}
      >
        <div>{this.state.msg}</div>
      </CallbackComponent>
    );
  }
}
```

In IE method onError called with message "No matching state found in storage". In other browsers onError didn't called. 

After I added `this.props.dispatch(push("/"))` call to onError handler sign in process completed with success:

```javascript
  onError = (err) => {
    // some code
    console.error(err);
    this.props.dispatch(push("/"));
  }
```

I don't know, Is this a bug? Is it related to oidc-client or redux-oidc? 
But for now this workaround works for me.

**Comment by maxmantz** [comment]
Sorry for the late reply. From your config I can see that you are using the middleware. The middleware is intended only for scenarios where you cannot set up silent renew. Other than thatm the `loadUser` helper should be used instead of the middleware. See [this line](https://github.com/maxmantz/redux-oidc-example/blob/master/src/store.js#L30) in the example app on how to set it up. Maybe this can fix your issue?

The other hint I get is that the error message says `No matching state found in storage`. This hints at the userManager's storage mechanism, which is sessionStorage by default. Maybe something goes wrong in IE11's session storage?

**Comment by maxmantz** [comment]
Closing this for now. Feel free to comment should the issue persist.
