### ISSUE TITLE
checkSession begin run hundreds of times per second

### ISSUE THREAD

**Issue by carleryd** [maxmantz/redux-oidc#91]
I set up my store with the userManager from redux-oidc, previously with version 2.2.1 and now with 3.0.0-beta14 and at both points the project I have experience a large bump in CPU usage when implementing the userManager, on a Macbook Pro 2017 the CPU usage increases from under 10% to between 15-25% and I have measured performance and see that checkSession, among other functions, are run extremely often.

Image of Chrome performance measurement with userManager
<img width="485" alt="screen shot 2018-02-01 at 10 49 11" src="https://user-images.githubusercontent.com/3730014/35674344-ab796e5a-0744-11e8-9016-f1011c3f7c94.png">

Image of Chrome performance measurement without userManager
<img width="433" alt="screen shot 2018-02-01 at 11 49 40" src="https://user-images.githubusercontent.com/3730014/35674791-1d183a54-0746-11e8-8b5e-7405b82ea221.png">

This is the code implementing the OIDC, without it the app runs fine.
```
const userManager = createUserManager(config.authConfig);

const store = createStore(reducers, composeWithDevTools(applyMiddleware(middleware, thunkMiddleware)));

loadUser(store, userManager);
```

with authConfig

```
  authConfig: {
    authority: "https://some-website.net",
    client_id: "js",
    redirect_uri: "https://some-website.net/callback",
    response_type: "id_token token",
    scope: "openid profile api1",
    post_logout_redirect_uri: "https://some-website.net",
    silent_redirect_uri: "https://some-website.net/silent_renew.html",
    automaticSilentRenew: true,
    filterProtocolClaims: true,
    loadUserInfo: true
  },
```

Any clue what is causing this? What is the checkSession actually doing and can it be run less often?

**Comment by maxmantz** [comment]
When upgrading from version 2 please don't use the OIDC middleware and the `loadUser` helper togehter. Only use the middleware if you don't have silent renew set up. Ohterwise drop it alltogether. This might cause this issue. Apart from that, your config looks fine.

**Comment by maxmantz** [comment]
Were you able to solve this issue?

**Comment by carleryd** [comment]
@maxmantz No unfortunately not, and I seem to be the only one the team with the issue. We stopped using createOidcMiddleware half a year ago. For others in my team the checkSession function is running about every second, but for me it runs about every 0.2ms(sometimes even faster, perhaps it just runs as fast as it possibly can).
What is controlling the interval in which it runs?

**Comment by maxmantz** [comment]
Maybe the `checkSession` function call is located at the oidc-client [https://github.com/IdentityModel/oidc-client-js] library. The `userManager` comes from there. So maybe raising an issue there can help you out. I don't enough about the inner workings of that library to be of much help here I'm afraid.
