### ISSUE TITLE
React-native proper example

### ISSUE THREAD

**Issue by PeterKottas** [maxmantz/redux-oidc#92]
Hi @maxmantz, hope you are well. First of all, yes I've seen https://github.com/maxmantz/redux-oidc/issues/25 but it seem to have become a bit crowded, it's more than 6 months old and the code samples there doesn't seem to be working with the latest versions of react-native. I am kind of hoping to end up with a proper, working example (ideally with silent_renew) that could be added to the documentation. So far I encountered a few problems and I was hoping you/somebody else would be able to shine some light on these:
1. Correct me if I am wrong, but even when webView seems like an obvious choice, it appears to be blocked by google auth and therefore popup sign in appears to be the only way to make this happen. Right?

2. With a popup, we handle all authentication in mobile web browser (which is great cause you reuse exiting UI), but what about the callback? Does it need to be a deep link via Linking react-native api. This I am unable to make to work, and it appears to be a rather hacky solution as it asks if you want to open the link in the app which can seem a bit dodgy by users. Am I missing something?

Btw, https://github.com/NerdySaiyan/redux-oidc-example-react-native seemed like a perfect starting point, but:
It doesn't work as of 2018, can't build the project, not sure what changed. It also specifies redirect_uri as localhost:3000 which is very odd cause there's no deep linking setup. I am not sure how it would work to pick up the token from the url. But again, maybe I am missing something. Any input would be highly appreciated. Thanks

**Comment by maxmantz** [comment]
Hello,

I know that the react-native examples have stalled lately. The reason is that the oidc-client-js library until now doesn't fully support native applications. It also seems like the implicit flow is not the desired method for authentication in native apps. Please read @leastprivilege 's post in this [pull request](https://github.com/IdentityModel/oidc-client-js/pull/410) for more information. The milestone for the PR is version 1.5.0. However, with the information given, it seems like native support is not desirable for this library.

**Comment by PeterKottas** [comment]
Ok, I see, damn that's quite a shame. I have yet to read that specification in full detail but given the overview of what it contains, would it maybe make sense to make it clear in the readme that this lib should not be used in react-native? Current readme states the opposite and while I know it is possible to a certain extent, it's apparently not the best practice. What do you think?

**Comment by PeterKottas** [comment]
If I understand it correctly, [this](https://github.com/FormidableLabs/react-native-app-auth) might provide the correct way of achieving the task at hand, right?

**Comment by maxmantz** [comment]
The current readme doesn't state anything opposite to what I just said here. But I will make a note in the readme clarifying this.

To your second point - it seems to be the way to go for react-native. However I haven't tried it yet.

**Comment by PeterKottas** [comment]
Yep sounds good, thanks again.
