### ISSUE TITLE
user object is undefined after successful redirect

### ISSUE THREAD

**Issue by kaitmore** [maxmantz/redux-oidc#95]
Hi there, thanks for all your great work on this library!

I was wondering if you had any clue to what I'm doing wrong here. I am using [Dex](https://github.com/coreos/dex) as my idp. I am able to sign in and am successfully redirected to my /callback route, however when I inspect the user object, it's undefined:

![image](https://user-images.githubusercontent.com/22768918/36822104-525ad03a-1cc4-11e8-8c04-3f9ef14864fa.png)

The url bar looks like:
```http://localhost:3000/callback?code=wvhdzqi2ergpw5szga2zoycza&state=9b4d6656a0f948948d938b8aff82a21e```

Here is my UserManager config:
```javascript
const config = {
  client_id: "example-app",
  redirect_uri: `http://localhost:3000/callback`,
  silent_redirect_uri: `http://localhost:3000/callback`,
  response_type: "code",
  scope: "openid profile",
  grant_type: "authorization_code",
  authority: "https://localhost:5556/dex",
  issuer: "https://localhost:5556/dex",
  metadata: {
    authorization_endpoint: "https://localhost:5556/dex/auth",
    jwks_uri: "https://localhost:5556/dex/keys"
  },
  post_logout_redirect_uri: `http://localhost:3000`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true
};

**Comment by maxmantz** [comment]
Hi,

it looks like the user object itself is not undefined, but rather its content (access_token, session_state, etc.) This suggest a problem with oidc-client and dex. I suggest you raise an issue there as I sadly can't help you here.

**Comment by kaitmore** [comment]
@maxmantz Ah yes, sorry, poor wording on my part. Thanks for taking a look!
