### ISSUE TITLE
Version 3.0.0-beta.16 throws Frame window timed out error

### ISSUE THREAD

**Issue by dyesseyumba** [maxmantz/redux-oidc#97]
Hi,
I just upgraded from `3.0.0-beta.14` to `3.0.0-beta.16`. Now when the silent renew try to update the access token I get this error message on the console:
 ```
Error: Frame window timed out at t._error (webpack-internal:///./node_modules/oidc-client/lib/oidc-client.min.js:74:25924) at t._timeout (webpack-internal:///./node_modules/oidc-client/lib/oidc-client.min.js:74:26359)
```
When I go back to `3.0.0-beta.14` everything is fine.

I’m using:
- react 16.2.0
- redux 3.2.0

**Comment by maxmantz** [comment]
There have been no change to the inner workings of this library during these updates. Did you maybe update the `oidc-client` dependency as well? Maybe the error comes from there. The source of the error (`oidc-client.min.js`) seems to indicate that.

**Comment by dyesseyumba** [comment]
Ok, I'll check on `oidc-client`.

**Comment by dsueltenfuss** [comment]
Where you able to resolve your issue? I am having the same problem with 3.0.0-beta.17.

**Comment by barrymichaeldoyle** [comment]
I'm still having this issue :(
